<script lang="ts">
	import CheckIcon from "@lucide/svelte/icons/check";
	import FolderIcon from "@lucide/svelte/icons/folder";
	import GitBranchIcon from "@lucide/svelte/icons/git-branch";
	import GitCommitIcon from "@lucide/svelte/icons/git-commit";
	import GithubIcon from "@lucide/svelte/icons/github";
	import { onDestroy, tick } from "svelte";
	import type { Workspace, WorkspaceValidationResult } from "$lib/api-types";
	import type {
		WorkspaceSelectionResult,
		WorkspaceSelectorState,
	} from "$lib/components/ide/conversation-composer.types";
	import { useAppContext } from "$lib/context/app-context.svelte";
	import {
		DropdownMenu,
		DropdownMenuContent,
		DropdownMenuItem,
		DropdownMenuSeparator,
		DropdownMenuTrigger,
	} from "$lib/components/ui/dropdown-menu";
	import { InputGroupButton } from "$lib/components/ui/input-group";
	import { Input } from "$lib/components/ui/input";
	import { NativeSelect } from "$lib/components/ui/native-select";

	type Props = {
		onStateChange: (state: WorkspaceSelectorState) => void;
	};

	let { onStateChange }: Props = $props();

	const workspaces = useAppContext().workspaces;

	let selectedWorkspaceOption = $state("new-workspace");
	let selectedWorkspaceBranch = $state("");
	let workspaceSourceInput = $state("");
	let showWorkspaceSourceInput = $state(false);
	let workspaceValidation = $state<WorkspaceValidationResult | null>(null);
	let validatingWorkspaceSource = $state(false);
	let setupMessage = $state<string | null>(null);
	let showWorkspaceSuggestions = $state(false);
	let selectedWorkspaceSuggestionIndex = $state(-1);
	let hasUserSelectedWorkspace = $state(false);
	let hasInitializedSelection = $state(false);

	let workspaceValidationDebounce: ReturnType<typeof setTimeout> | null = null;
	let workspaceValidationRequestId = 0;
	let workspaceSuggestionsCloseTimeout: ReturnType<typeof setTimeout> | null = null;

	const availableWorkspaces = $derived.by(() =>
		workspaces.list.filter((workspace) => !workspace.autoGenerated),
	);
	const loadingWorkspaces = $derived.by(() => workspaces.status === "loading");
	const requiresSourceInput = $derived.by(
		() => selectedWorkspaceOption === "local-directory" || selectedWorkspaceOption === "git-repo",
	);
	const selectedExistingWorkspace = $derived.by(() => {
		if (!selectedWorkspaceOption.startsWith("existing:")) {
			return null;
		}

		const selectedWorkspaceId = selectedWorkspaceOption.slice("existing:".length);
		return availableWorkspaces.find((workspace) => workspace.id === selectedWorkspaceId) ?? null;
	});
	const existingWorkspaceIsGithub = $derived.by(
		() => selectedExistingWorkspace !== null && isGithubWorkspace(selectedExistingWorkspace),
	);
	const showBranchSelector = $derived.by(() => selectedWorkspaceOption !== "new-workspace");
	const availableWorkspaceBranches = $derived.by(() => {
		if (selectedWorkspaceOption === "local-directory") {
			return ["main", "discobot-session", "feature/local-workspace"];
		}

		if (selectedWorkspaceOption === "git-repo") {
			return ["main", "develop", "release"];
		}

		if (selectedExistingWorkspace?.sourceType === "git") {
			return ["main", "develop", "feature/workspace-sync"];
		}

		return ["main", "discobot-session", "feature/workspace-setup"];
	});
	const workspaceSourceType = $derived.by(() => {
		return selectedWorkspaceOption === "git-repo" ? "git" : "local";
	});
	const workspaceSuggestions = $derived.by(() => workspaceValidation?.suggestions ?? []);
	const workspaceSourceIsValid = $derived.by(() => {
		if (!requiresSourceInput || !showWorkspaceSourceInput) {
			return true;
		}

		if (workspaceSourceInput.trim().length === 0 || validatingWorkspaceSource) {
			return false;
		}

		return workspaceValidation?.valid ?? false;
	});
	const workspaceValidationMessage = $derived.by(() => {
		if (!requiresSourceInput || !showWorkspaceSourceInput) {
			return null;
		}

		if (workspaceSourceInput.trim().length === 0) {
			return null;
		}

		if (validatingWorkspaceSource) {
			return "Validating workspace...";
		}

		if (!workspaceValidation) {
			return null;
		}

		if (!workspaceValidation.valid) {
			return workspaceValidation.error || "Enter a valid workspace path.";
		}

		switch (workspaceValidation.classification) {
			case "new":
				return "A new directory will be created and initialized as a git repository.";
			case "empty":
				return "Empty directory is valid. It will be initialized as a git repository.";
			case "existing_git":
				return "Existing git repository detected.";
			case "cloneable":
				return "Repository is cloneable.";
			default:
				return null;
		}
	});
	const snapshot = $derived.by<WorkspaceSelectorState>(() => ({
		selectedWorkspaceOption,
		selectedWorkspaceBranch,
		requiresSourceInput,
		workspaceSourceInput,
		workspaceSourceType,
		workspaceValidation,
		workspaceSourceIsValid,
		workspaceValidationMessage,
		validatingWorkspaceSource,
		setupMessage,
	}));

	function shortenHomePath(path: string): string {
		const homeMatch = path.match(/^(\/home\/[^/]+|\/Users\/[^/]+)(\/.*)?$/);
		if (homeMatch) {
			const rest = homeMatch[2] || "";
			return `~${rest}`;
		}
		return path;
	}

	function getWorkspaceOptionLabel(workspace: Workspace): string {
		return workspace.displayName || shortenHomePath(workspace.path);
	}

	function isGithubWorkspace(workspace: Workspace): boolean {
		if (workspace.sourceType !== "git") {
			return false;
		}

		const value = `${workspace.path} ${workspace.displayName || ""}`.toLowerCase();
		return value.includes("github.com") || value.includes("github");
	}

	function isGithubRepoInput(value: string): boolean {
		const trimmed = value.trim().toLowerCase();
		if (trimmed.length === 0) {
			return false;
		}

		if (trimmed.startsWith("github.com/") || trimmed.includes("github.com")) {
			return true;
		}

		return /^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})\/[A-Za-z0-9._-]+$/.test(trimmed);
	}

	function clearWorkspaceValidationDebounce() {
		if (!workspaceValidationDebounce) {
			return;
		}

		clearTimeout(workspaceValidationDebounce);
		workspaceValidationDebounce = null;
	}

	function clearWorkspaceSuggestionsCloseTimeout() {
		if (!workspaceSuggestionsCloseTimeout) {
			return;
		}

		clearTimeout(workspaceSuggestionsCloseTimeout);
		workspaceSuggestionsCloseTimeout = null;
	}

	function focusWorkspaceSourceInput() {
		const input = document.getElementById("session-setup-source-inline") as HTMLInputElement | null;
		input?.focus();
	}

	function resetSourceInputState() {
		showWorkspaceSourceInput = false;
		workspaceSourceInput = "";
		workspaceValidation = null;
		validatingWorkspaceSource = false;
		clearWorkspaceValidationDebounce();
		clearWorkspaceSuggestionsCloseTimeout();
		showWorkspaceSuggestions = false;
		selectedWorkspaceSuggestionIndex = -1;
	}

	function handleWorkspaceOptionChange(nextOption: string) {
		hasUserSelectedWorkspace = true;
		selectedWorkspaceOption = nextOption;
		selectedWorkspaceBranch = "";
		setupMessage = null;
		workspaceValidation = null;
		validatingWorkspaceSource = false;
		clearWorkspaceValidationDebounce();
		clearWorkspaceSuggestionsCloseTimeout();
		showWorkspaceSuggestions = false;
		selectedWorkspaceSuggestionIndex = -1;

		if (nextOption === "local-directory" || nextOption === "git-repo") {
			workspaceSourceInput = "";
			showWorkspaceSourceInput = true;
			void tick().then(() => {
				focusWorkspaceSourceInput();
			});
			return;
		}

		showWorkspaceSourceInput = false;
		workspaceSourceInput = "";
	}

	function handleWorkspaceSourceInputChange(value: string) {
		workspaceSourceInput = value;
		setupMessage = null;
		showWorkspaceSuggestions = true;
		selectedWorkspaceSuggestionIndex = -1;
	}

	function handleWorkspaceSourceFocus() {
		clearWorkspaceSuggestionsCloseTimeout();
		showWorkspaceSuggestions = true;
	}

	function handleWorkspaceSourceBlur() {
		clearWorkspaceSuggestionsCloseTimeout();
		workspaceSuggestionsCloseTimeout = setTimeout(() => {
			showWorkspaceSuggestions = false;
			selectedWorkspaceSuggestionIndex = -1;
			workspaceSuggestionsCloseTimeout = null;
		}, 120);
	}

	function applyWorkspaceSuggestion(suggestionValue: string) {
		workspaceSourceInput = suggestionValue;
		setupMessage = null;
		showWorkspaceSuggestions = false;
		selectedWorkspaceSuggestionIndex = -1;
		focusWorkspaceSourceInput();
	}

	function acceptWorkspaceSuggestion(preferFirst: boolean): boolean {
		if (!showWorkspaceSuggestions || workspaceSuggestions.length === 0) {
			return false;
		}

		let suggestionIndex = selectedWorkspaceSuggestionIndex;
		if (suggestionIndex < 0 && preferFirst) {
			suggestionIndex = 0;
		}

		if (suggestionIndex < 0 || suggestionIndex >= workspaceSuggestions.length) {
			return false;
		}

		applyWorkspaceSuggestion(workspaceSuggestions[suggestionIndex].value);
		return true;
	}

	function handleSourceKeydown(event: KeyboardEvent) {
		if (event.key === "ArrowDown") {
			if (!showWorkspaceSuggestions || workspaceSuggestions.length === 0) {
				return;
			}
			event.preventDefault();
			selectedWorkspaceSuggestionIndex = Math.min(
				selectedWorkspaceSuggestionIndex + 1,
				workspaceSuggestions.length - 1,
			);
			return;
		}

		if (event.key === "ArrowUp") {
			if (!showWorkspaceSuggestions || workspaceSuggestions.length === 0) {
				return;
			}
			event.preventDefault();
			selectedWorkspaceSuggestionIndex = Math.max(selectedWorkspaceSuggestionIndex - 1, -1);
			return;
		}

		if (event.key === "Escape") {
			event.preventDefault();
			showWorkspaceSuggestions = false;
			selectedWorkspaceSuggestionIndex = -1;
			selectedWorkspaceOption = "new-workspace";
			selectedWorkspaceBranch = "";
			workspaceSourceInput = "";
			showWorkspaceSourceInput = false;
			setupMessage = null;
			workspaceValidation = null;
			return;
		}

		if (event.key === "Enter") {
			if (acceptWorkspaceSuggestion(true)) {
				event.preventDefault();
			}
			showWorkspaceSuggestions = false;
			selectedWorkspaceSuggestionIndex = -1;
			return;
		}

		if (event.key === "Tab") {
			if (acceptWorkspaceSuggestion(true)) {
				event.preventDefault();
			}
		}
	}

	export function getState(): WorkspaceSelectorState {
		return snapshot;
	}

	export function resetForNewSession() {
		hasUserSelectedWorkspace = false;
		hasInitializedSelection = false;
		selectedWorkspaceOption = "new-workspace";
		selectedWorkspaceBranch = "";
		setupMessage = null;
		resetSourceInputState();
	}

	export async function getWorkspaceSelection(): Promise<WorkspaceSelectionResult> {
		if (selectedWorkspaceOption.startsWith("existing:")) {
			const workspaceId = selectedWorkspaceOption.slice("existing:".length);
			if (!workspaces.list.some((workspace) => workspace.id === workspaceId)) {
				setupMessage = "Select an existing workspace.";
				return {
					ready: false,
					workspaceId: null,
					workspaceType: null,
					workspacePath: null,
				};
			}

			setupMessage = null;
			return {
				ready: true,
				workspaceId,
				workspaceType: null,
				workspacePath: null,
			};
		}

		if (!requiresSourceInput) {
			setupMessage = null;
			return {
				ready: true,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		if (validatingWorkspaceSource) {
			setupMessage = "Validating workspace...";
			return {
				ready: false,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		if (!workspaceValidation || workspaceValidation.sourceType !== workspaceSourceType) {
			setupMessage = workspaceSourceType === "git"
				? "Enter a Git repository URL."
				: "Enter a local directory path.";
			return {
				ready: false,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		if (!workspaceValidation.valid) {
			setupMessage = workspaceValidation.error ||
				(workspaceSourceType === "git"
					? "Enter a valid Git repository URL."
					: "Enter a valid local directory path.");
			return {
				ready: false,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		const normalizedPath = workspaceValidation.path.trim();
		if (normalizedPath.length === 0) {
			setupMessage = workspaceSourceType === "git"
				? "Enter a Git repository URL."
				: "Enter a local directory path.";
			return {
				ready: false,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		setupMessage = null;
		return {
			ready: true,
			workspaceId: null,
			workspaceType: workspaceSourceType,
			workspacePath: normalizedPath,
		};
	}

	$effect(() => {
		if (workspaces.status === "idle") {
			void workspaces.refresh();
		}
	});

	$effect(() => {
		const workspaces = availableWorkspaces;
		if (workspaces.length === 0) {
			if (selectedWorkspaceOption.startsWith("existing:")) {
				selectedWorkspaceOption = "new-workspace";
			}
			return;
		}

		const preferredWorkspace = workspaces.find((workspace) => workspace.status === "ready") || workspaces[0];
		if (!preferredWorkspace) {
			return;
		}

		if (selectedWorkspaceOption.startsWith("existing:")) {
			const selectedWorkspaceId = selectedWorkspaceOption.slice("existing:".length);
			if (!workspaces.some((workspace) => workspace.id === selectedWorkspaceId) && !hasUserSelectedWorkspace) {
				selectedWorkspaceOption = `existing:${preferredWorkspace.id}`;
			}
			return;
		}

		if (!hasUserSelectedWorkspace && !hasInitializedSelection && selectedWorkspaceOption === "new-workspace") {
			hasInitializedSelection = true;
			selectedWorkspaceOption = `existing:${preferredWorkspace.id}`;
		}
	});

	$effect(() => {
		if (!showBranchSelector) {
			selectedWorkspaceBranch = "";
			return;
		}

		if (
			selectedWorkspaceBranch.length > 0 &&
			!availableWorkspaceBranches.includes(selectedWorkspaceBranch)
		) {
			selectedWorkspaceBranch = "";
		}
	});

	$effect(() => {
		if (!requiresSourceInput || !showWorkspaceSourceInput) {
			clearWorkspaceValidationDebounce();
			validatingWorkspaceSource = false;
			workspaceValidation = null;
			showWorkspaceSuggestions = false;
			selectedWorkspaceSuggestionIndex = -1;
			return;
		}

		const currentInput = workspaceSourceInput;
		if (currentInput.trim().length === 0) {
			clearWorkspaceValidationDebounce();
			validatingWorkspaceSource = false;
			workspaceValidation = null;
			selectedWorkspaceSuggestionIndex = -1;
			return;
		}

		clearWorkspaceValidationDebounce();
		validatingWorkspaceSource = true;
		const requestId = workspaceValidationRequestId + 1;
		workspaceValidationRequestId = requestId;

		workspaceValidationDebounce = setTimeout(async () => {
			try {
				const result = await workspaces.validate(currentInput, workspaceSourceType);

				if (workspaceValidationRequestId !== requestId) {
					return;
				}

				workspaceValidation = result;
			} catch (error) {
				if (workspaceValidationRequestId !== requestId) {
					return;
				}

				workspaceValidation = {
					path: currentInput,
					sourceType: workspaceSourceType,
					valid: false,
					classification: "invalid",
					error: error instanceof Error ? error.message : "Failed to validate workspace.",
					suggestions: [],
				};
			} finally {
				if (workspaceValidationRequestId === requestId) {
					validatingWorkspaceSource = false;
				}
			}
		}, 250);
	});

	$effect(() => {
		onStateChange(snapshot);
	});

	onDestroy(() => {
		clearWorkspaceValidationDebounce();
		clearWorkspaceSuggestionsCloseTimeout();
	});
</script>

<div class="flex items-center gap-1.5">
	{#if showWorkspaceSourceInput && requiresSourceInput}
		{#if workspaceSourceType === "local"}
			<FolderIcon class="size-4 text-muted-foreground" />
		{:else if isGithubRepoInput(workspaceSourceInput)}
			<GithubIcon class="size-4 text-muted-foreground" />
		{:else}
			<GitCommitIcon class="size-4 text-muted-foreground" />
		{/if}
	{:else if selectedWorkspaceOption === "local-directory"}
		<FolderIcon class="size-4 text-muted-foreground" />
	{:else if selectedWorkspaceOption === "git-repo"}
		<GithubIcon class="size-4 text-muted-foreground" />
	{:else if selectedWorkspaceOption.startsWith("existing:")}
		{#if selectedExistingWorkspace?.sourceType === "local"}
			<FolderIcon class="size-4 text-muted-foreground" />
		{:else if existingWorkspaceIsGithub}
			<GithubIcon class="size-4 text-muted-foreground" />
		{:else}
			<GitCommitIcon class="size-4 text-muted-foreground" />
		{/if}
	{:else}
		<FolderIcon class="size-4 text-muted-foreground" />
	{/if}

	{#if showWorkspaceSourceInput && requiresSourceInput}
		<div class="relative">
			<Input
				id="session-setup-source-inline"
				class="h-8 w-[260px] text-xs"
				value={workspaceSourceInput}
				placeholder={
					workspaceSourceType === "local"
						? "~/projects/my-app"
						: "https://github.com/org/repo or org/repo"
				}
				onfocus={handleWorkspaceSourceFocus}
				onblur={handleWorkspaceSourceBlur}
				oninput={(event) => {
					handleWorkspaceSourceInputChange((event.currentTarget as HTMLInputElement).value);
				}}
				onkeydown={handleSourceKeydown}
			/>

			{#if showWorkspaceSuggestions && workspaceSuggestions.length > 0}
				<div class="absolute right-0 top-full z-50 mt-1 max-h-56 w-[260px] overflow-y-auto rounded-md border border-border bg-popover shadow-lg">
					{#each workspaceSuggestions as suggestion, index (suggestion.value)}
						<button
							type="button"
							class={`flex w-full items-center justify-between gap-2 px-3 py-2 text-left text-xs hover:bg-accent ${index === selectedWorkspaceSuggestionIndex ? "bg-accent" : ""} ${suggestion.valid ? "" : "opacity-70"}`}
							onmouseenter={() => {
								selectedWorkspaceSuggestionIndex = index;
							}}
							onmousedown={(event) => {
								event.preventDefault();
								applyWorkspaceSuggestion(suggestion.value);
							}}
						>
							<span class="truncate font-mono">{suggestion.value}</span>
							{#if suggestion.valid}
								<CheckIcon class="size-3.5 text-primary" />
							{/if}
						</button>
					{/each}
				</div>
			{/if}
		</div>
	{:else}
		<NativeSelect
			id="session-setup-workspace-inline"
			class="h-8 w-[240px] text-xs"
			value={selectedWorkspaceOption}
			disabled={loadingWorkspaces}
			onchange={(event) => {
				handleWorkspaceOptionChange((event.currentTarget as HTMLSelectElement).value);
			}}
		>
			{#if availableWorkspaces.length > 0}
				<optgroup label="Existing workspaces">
					{#each availableWorkspaces as workspace (workspace.id)}
						<option value={`existing:${workspace.id}`}>
							{getWorkspaceOptionLabel(workspace)}
						</option>
					{/each}
				</optgroup>
			{/if}
			<optgroup label="Create new">
				<option value="new-workspace">Empty Workspace</option>
				<option value="local-directory">Local Directory</option>
				<option value="git-repo">GitHub Repo</option>
			</optgroup>
		</NativeSelect>
	{/if}
</div>

{#if showBranchSelector}
	<DropdownMenu>
		<DropdownMenuTrigger class="tauri-no-drag">
			<InputGroupButton
				type="button"
				size="icon-sm"
				variant="ghost"
				aria-label="Select branch"
				title={selectedWorkspaceBranch || "No branch selected"}
			>
				<GitBranchIcon
					class={`size-4 ${selectedWorkspaceBranch ? "text-foreground" : "text-muted-foreground"}`}
				/>
			</InputGroupButton>
		</DropdownMenuTrigger>
		<DropdownMenuContent align="end" class="w-56">
			<DropdownMenuItem
				onclick={() => {
					selectedWorkspaceBranch = "";
				}}
				class="justify-between"
			>
				<span>No branch</span>
				{#if selectedWorkspaceBranch === ""}
					<CheckIcon class="size-3.5 text-primary" />
				{/if}
			</DropdownMenuItem>
			<DropdownMenuSeparator />
			{#each availableWorkspaceBranches as branch (branch)}
				<DropdownMenuItem
					onclick={() => {
						selectedWorkspaceBranch = branch;
					}}
					class="justify-between"
				>
					<span class="truncate">{branch}</span>
					{#if selectedWorkspaceBranch === branch}
						<CheckIcon class="size-3.5 text-primary" />
					{/if}
				</DropdownMenuItem>
			{/each}
		</DropdownMenuContent>
	</DropdownMenu>
{/if}
