<script lang="ts">
	import CheckIcon from "@lucide/svelte/icons/check";
	import FolderIcon from "@lucide/svelte/icons/folder";
	import GitBranchIcon from "@lucide/svelte/icons/git-branch";
	import GitCommitIcon from "@lucide/svelte/icons/git-commit";
	import GithubIcon from "@lucide/svelte/icons/github";
	import { onDestroy, tick } from "svelte";
	import type { Workspace } from "$lib/api-types";
	import type { WorkspaceSelectionResult } from "$lib/components/ide/conversation-composer.types";
	import { useAppContext } from "$lib/context/app-context.svelte";
	import { useSessionContext } from "$lib/context/session-context.svelte";
	import {
		DropdownMenu,
		DropdownMenuContent,
		DropdownMenuItem,
		DropdownMenuSeparator,
		DropdownMenuTrigger,
	} from "$lib/components/ui/dropdown-menu";
	import { InputGroupButton } from "$lib/components/ui/input-group";
	import { Input } from "$lib/components/ui/input";
	import { NativeSelect } from "$lib/components/ui/native-select";

	let { fullWidth = false }: { fullWidth?: boolean } = $props();

	const workspaces = useAppContext().workspaces;
	const session = useSessionContext();
	const sessionView = session.ui;

	let showWorkspaceSuggestions = $state(false);
	let selectedWorkspaceSuggestionIndex = $state(-1);
	let hasUserSelectedWorkspace = $state(false);
	let hasInitializedSelection = $state(false);
	let workspaceSelectRef = $state<HTMLSelectElement | null>(null);

	let workspaceValidationDebounce: ReturnType<typeof setTimeout> | null = null;
	let workspaceValidationRequestId = 0;
	let workspaceSuggestionsCloseTimeout: ReturnType<typeof setTimeout> | null = null;

	const availableWorkspaces = $derived.by(() =>
		workspaces.list.filter((workspace) => !workspace.autoGenerated),
	);
	const loadingWorkspaces = $derived.by(() => workspaces.status === "loading");
	const requiresSourceInput = $derived.by(() => sessionView.pendingWorkspaceRequiresSourceInput);
	const selectedExistingWorkspace = $derived.by(() => {
		if (!sessionView.pendingWorkspaceOption.startsWith("existing:")) {
			return null;
		}

		const selectedWorkspaceId = sessionView.pendingWorkspaceOption.slice("existing:".length);
		return availableWorkspaces.find((workspace) => workspace.id === selectedWorkspaceId) ?? null;
	});
	const existingWorkspaceIsGithub = $derived.by(
		() => selectedExistingWorkspace !== null && isGithubWorkspace(selectedExistingWorkspace),
	);
	const showBranchSelector = $derived.by(() => sessionView.pendingWorkspaceOption !== "new-workspace");
	const availableWorkspaceBranches = $derived.by(() => {
		if (sessionView.pendingWorkspaceOption === "local-directory") {
			return ["main", "discobot-session", "feature/local-workspace"];
		}

		if (sessionView.pendingWorkspaceOption === "git-repo") {
			return ["main", "develop", "release"];
		}

		if (selectedExistingWorkspace?.sourceType === "git") {
			return ["main", "develop", "feature/workspace-sync"];
		}

		return ["main", "discobot-session", "feature/workspace-setup"];
	});
	const workspaceSourceType = $derived.by(() => sessionView.pendingWorkspaceSourceType);
	const workspaceSuggestions = $derived.by(() => sessionView.pendingWorkspaceValidation?.suggestions ?? []);

	function shortenHomePath(path: string): string {
		const homeMatch = path.match(/^(\/home\/[^/]+|\/Users\/[^/]+)(\/.*)?$/);
		if (homeMatch) {
			const rest = homeMatch[2] || "";
			return `~${rest}`;
		}
		return path;
	}

	function getWorkspaceOptionLabel(workspace: Workspace): string {
		return workspace.displayName || shortenHomePath(workspace.path);
	}

	function isGithubWorkspace(workspace: Workspace): boolean {
		if (workspace.sourceType !== "git") {
			return false;
		}

		const value = `${workspace.path} ${workspace.displayName || ""}`.toLowerCase();
		return value.includes("github.com") || value.includes("github");
	}

	function isGithubRepoInput(value: string): boolean {
		const trimmed = value.trim().toLowerCase();
		if (trimmed.length === 0) {
			return false;
		}

		if (trimmed.startsWith("github.com/") || trimmed.includes("github.com")) {
			return true;
		}

		return /^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})\/[A-Za-z0-9._-]+$/.test(trimmed);
	}

	function clearWorkspaceValidationDebounce() {
		if (!workspaceValidationDebounce) {
			return;
		}

		clearTimeout(workspaceValidationDebounce);
		workspaceValidationDebounce = null;
	}

	function clearWorkspaceSuggestionsCloseTimeout() {
		if (!workspaceSuggestionsCloseTimeout) {
			return;
		}

		clearTimeout(workspaceSuggestionsCloseTimeout);
		workspaceSuggestionsCloseTimeout = null;
	}

	function focusWorkspaceSourceInput() {
		const input = document.getElementById("session-setup-source-inline") as HTMLInputElement | null;
		input?.focus();
	}

	function resetToWorkspaceDropdown() {
		showWorkspaceSuggestions = false;
		selectedWorkspaceSuggestionIndex = -1;
		sessionView.setPendingWorkspaceOption("new-workspace");
		sessionView.setPendingWorkspaceBranch("");
		sessionView.setPendingWorkspaceSourceInput("");
		sessionView.setPendingWorkspaceSetupMessage(null);
		sessionView.setPendingWorkspaceValidation(null);
		sessionView.setPendingWorkspaceValidating(false);
		clearWorkspaceValidationDebounce();
		clearWorkspaceSuggestionsCloseTimeout();
	}

	function openWorkspaceDropdown() {
		const select = workspaceSelectRef as (HTMLSelectElement & { showPicker?: () => void }) | null;
		if (!select || select.disabled) {
			return;
		}

		select.focus();
		if (typeof select.showPicker === "function") {
			try {
				select.showPicker();
				return;
			} catch {
				// Fall back to a click when showPicker is unavailable.
			}
		}

		select.click();
	}

	async function handleWorkspaceIconClick() {
		resetToWorkspaceDropdown();
		await tick();
		openWorkspaceDropdown();
	}

	function handleWorkspaceOptionChange(nextOption: string) {
		hasUserSelectedWorkspace = true;
		sessionView.setPendingWorkspaceOption(nextOption);
		sessionView.setPendingWorkspaceBranch("");
		sessionView.setPendingWorkspaceSetupMessage(null);
		sessionView.setPendingWorkspaceValidation(null);
		sessionView.setPendingWorkspaceValidating(false);
		clearWorkspaceValidationDebounce();
		clearWorkspaceSuggestionsCloseTimeout();
		showWorkspaceSuggestions = false;
		selectedWorkspaceSuggestionIndex = -1;

		if (nextOption === "local-directory" || nextOption === "git-repo") {
			sessionView.setPendingWorkspaceSourceInput("");
			void tick().then(() => {
				focusWorkspaceSourceInput();
			});
			return;
		}

		sessionView.setPendingWorkspaceSourceInput("");
	}

	function handleWorkspaceSourceInputChange(value: string) {
		sessionView.setPendingWorkspaceSourceInput(value);
		sessionView.setPendingWorkspaceSetupMessage(null);
		showWorkspaceSuggestions = true;
		selectedWorkspaceSuggestionIndex = -1;
	}

	function handleWorkspaceSourceFocus() {
		clearWorkspaceSuggestionsCloseTimeout();
		showWorkspaceSuggestions = true;
	}

	function handleWorkspaceSourceBlur() {
		clearWorkspaceSuggestionsCloseTimeout();
		workspaceSuggestionsCloseTimeout = setTimeout(() => {
			showWorkspaceSuggestions = false;
			selectedWorkspaceSuggestionIndex = -1;
			workspaceSuggestionsCloseTimeout = null;
		}, 120);
	}

	function applyWorkspaceSuggestion(suggestionValue: string) {
		sessionView.setPendingWorkspaceSourceInput(suggestionValue);
		sessionView.setPendingWorkspaceSetupMessage(null);
		showWorkspaceSuggestions = false;
		selectedWorkspaceSuggestionIndex = -1;
		focusWorkspaceSourceInput();
	}

	function acceptWorkspaceSuggestion(preferFirst: boolean): boolean {
		if (!showWorkspaceSuggestions || workspaceSuggestions.length === 0) {
			return false;
		}

		let suggestionIndex = selectedWorkspaceSuggestionIndex;
		if (suggestionIndex < 0 && preferFirst) {
			suggestionIndex = 0;
		}

		if (suggestionIndex < 0 || suggestionIndex >= workspaceSuggestions.length) {
			return false;
		}

		applyWorkspaceSuggestion(workspaceSuggestions[suggestionIndex].value);
		return true;
	}

	function handleSourceKeydown(event: KeyboardEvent) {
		if (event.key === "ArrowDown") {
			if (!showWorkspaceSuggestions || workspaceSuggestions.length === 0) {
				return;
			}
			event.preventDefault();
			selectedWorkspaceSuggestionIndex = Math.min(
				selectedWorkspaceSuggestionIndex + 1,
				workspaceSuggestions.length - 1,
			);
			return;
		}

		if (event.key === "ArrowUp") {
			if (!showWorkspaceSuggestions || workspaceSuggestions.length === 0) {
				return;
			}
			event.preventDefault();
			selectedWorkspaceSuggestionIndex = Math.max(selectedWorkspaceSuggestionIndex - 1, -1);
			return;
		}

		if (event.key === "Escape") {
			event.preventDefault();
			resetToWorkspaceDropdown();
			return;
		}

		if (event.key === "Enter") {
			if (acceptWorkspaceSuggestion(true)) {
				event.preventDefault();
			}
			showWorkspaceSuggestions = false;
			selectedWorkspaceSuggestionIndex = -1;
			return;
		}

		if (event.key === "Tab") {
			if (acceptWorkspaceSuggestion(true)) {
				event.preventDefault();
			}
		}
	}

	export function resetForNewSession() {
		hasUserSelectedWorkspace = false;
		hasInitializedSelection = false;
		sessionView.resetPendingWorkspaceSetup();
		clearWorkspaceValidationDebounce();
		clearWorkspaceSuggestionsCloseTimeout();
		showWorkspaceSuggestions = false;
		selectedWorkspaceSuggestionIndex = -1;
	}

	export async function getWorkspaceSelection(): Promise<WorkspaceSelectionResult> {
		if (sessionView.pendingWorkspaceOption.startsWith("existing:")) {
			const workspaceId = sessionView.pendingWorkspaceOption.slice("existing:".length);
			if (!workspaces.list.some((workspace) => workspace.id === workspaceId)) {
				sessionView.setPendingWorkspaceSetupMessage("Select an existing workspace.");
				return {
					ready: false,
					workspaceId: null,
					workspaceType: null,
					workspacePath: null,
				};
			}

			sessionView.setPendingWorkspaceSetupMessage(null);
			return {
				ready: true,
				workspaceId,
				workspaceType: null,
				workspacePath: null,
			};
		}

		if (!requiresSourceInput) {
			sessionView.setPendingWorkspaceSetupMessage(null);
			return {
				ready: true,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		if (sessionView.pendingWorkspaceValidating) {
			sessionView.setPendingWorkspaceSetupMessage("Validating workspace...");
			return {
				ready: false,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		if (
			!sessionView.pendingWorkspaceValidation ||
			sessionView.pendingWorkspaceValidation.sourceType !== workspaceSourceType
		) {
			sessionView.setPendingWorkspaceSetupMessage(
				workspaceSourceType === "git"
					? "Enter a Git repository URL."
					: "Enter a local directory path.",
			);
			return {
				ready: false,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		if (!sessionView.pendingWorkspaceValidation.valid) {
			sessionView.setPendingWorkspaceSetupMessage(
				sessionView.pendingWorkspaceValidation.error ||
					(workspaceSourceType === "git"
						? "Enter a valid Git repository URL."
						: "Enter a valid local directory path."),
			);
			return {
				ready: false,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		const normalizedPath = sessionView.pendingWorkspaceValidation.path.trim();
		if (normalizedPath.length === 0) {
			sessionView.setPendingWorkspaceSetupMessage(
				workspaceSourceType === "git"
					? "Enter a Git repository URL."
					: "Enter a local directory path.",
			);
			return {
				ready: false,
				workspaceId: null,
				workspaceType: null,
				workspacePath: null,
			};
		}

		sessionView.setPendingWorkspaceSetupMessage(null);
		return {
			ready: true,
			workspaceId: null,
			workspaceType: workspaceSourceType,
			workspacePath: normalizedPath,
		};
	}

	$effect(() => {
		if (workspaces.status === "idle") {
			void workspaces.refresh();
		}
	});

	$effect(() => {
		const workspacesList = availableWorkspaces;
		if (workspacesList.length === 0) {
			if (sessionView.pendingWorkspaceOption.startsWith("existing:")) {
				sessionView.setPendingWorkspaceOption("new-workspace");
			}
			return;
		}

		const preferredWorkspace =
			workspacesList.find((workspace) => workspace.status === "ready") || workspacesList[0];
		if (!preferredWorkspace) {
			return;
		}

		if (sessionView.pendingWorkspaceOption.startsWith("existing:")) {
			const selectedWorkspaceId = sessionView.pendingWorkspaceOption.slice("existing:".length);
			if (
				!workspacesList.some((workspace) => workspace.id === selectedWorkspaceId) &&
				!hasUserSelectedWorkspace
			) {
				sessionView.setPendingWorkspaceOption(`existing:${preferredWorkspace.id}`);
			}
			return;
		}

		if (
			!hasUserSelectedWorkspace &&
			!hasInitializedSelection &&
			sessionView.pendingWorkspaceOption === "new-workspace"
		) {
			hasInitializedSelection = true;
			sessionView.setPendingWorkspaceOption(`existing:${preferredWorkspace.id}`);
		}
	});

	$effect(() => {
		if (!showBranchSelector) {
			sessionView.setPendingWorkspaceBranch("");
			return;
		}

		if (
			sessionView.pendingWorkspaceBranch.length > 0 &&
			!availableWorkspaceBranches.includes(sessionView.pendingWorkspaceBranch)
		) {
			sessionView.setPendingWorkspaceBranch("");
		}
	});

	$effect(() => {
		if (!requiresSourceInput) {
			clearWorkspaceValidationDebounce();
			sessionView.setPendingWorkspaceValidating(false);
			sessionView.setPendingWorkspaceValidation(null);
			showWorkspaceSuggestions = false;
			selectedWorkspaceSuggestionIndex = -1;
			return;
		}

		const currentInput = sessionView.pendingWorkspaceSourceInput;
		if (currentInput.trim().length === 0) {
			clearWorkspaceValidationDebounce();
			sessionView.setPendingWorkspaceValidating(false);
			sessionView.setPendingWorkspaceValidation(null);
			selectedWorkspaceSuggestionIndex = -1;
			return;
		}

		clearWorkspaceValidationDebounce();
		sessionView.setPendingWorkspaceValidating(true);
		const requestId = workspaceValidationRequestId + 1;
		workspaceValidationRequestId = requestId;

		workspaceValidationDebounce = setTimeout(async () => {
			try {
				const result = await workspaces.validate(currentInput, workspaceSourceType);

				if (workspaceValidationRequestId !== requestId) {
					return;
				}

				sessionView.setPendingWorkspaceValidation(result);
			} catch (error) {
				if (workspaceValidationRequestId !== requestId) {
					return;
				}

				sessionView.setPendingWorkspaceValidation({
					path: currentInput,
					sourceType: workspaceSourceType,
					valid: false,
					classification: "invalid",
					error: error instanceof Error ? error.message : "Failed to validate workspace.",
					suggestions: [],
				});
			} finally {
				if (workspaceValidationRequestId === requestId) {
					sessionView.setPendingWorkspaceValidating(false);
				}
			}
		}, 250);
	});

	onDestroy(() => {
		clearWorkspaceValidationDebounce();
		clearWorkspaceSuggestionsCloseTimeout();
	});
</script>

<div class="flex items-center gap-1.5 {fullWidth ? 'flex-1' : ''}">
	{#if requiresSourceInput}
		<button
			type="button"
			class="-m-1 inline-flex items-center justify-center rounded-sm p-1 text-muted-foreground transition-colors hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
			aria-label="Return to workspace dropdown"
			title="Return to workspace dropdown"
			onclick={() => {
				void handleWorkspaceIconClick();
			}}
		>
			{#if workspaceSourceType === "local"}
				<FolderIcon class="size-4" />
			{:else if isGithubRepoInput(sessionView.pendingWorkspaceSourceInput)}
				<GithubIcon class="size-4" />
			{:else}
				<GitCommitIcon class="size-4" />
			{/if}
		</button>
	{:else if sessionView.pendingWorkspaceOption === "local-directory"}
		<FolderIcon class="size-4 text-muted-foreground" />
	{:else if sessionView.pendingWorkspaceOption === "git-repo"}
		<GithubIcon class="size-4 text-muted-foreground" />
	{:else if sessionView.pendingWorkspaceOption.startsWith("existing:")}
		{#if selectedExistingWorkspace?.sourceType === "local"}
			<FolderIcon class="size-4 text-muted-foreground" />
		{:else if existingWorkspaceIsGithub}
			<GithubIcon class="size-4 text-muted-foreground" />
		{:else}
			<GitCommitIcon class="size-4 text-muted-foreground" />
		{/if}
	{:else}
		<FolderIcon class="size-4 text-muted-foreground" />
	{/if}

	{#if requiresSourceInput}
		<div class="relative {fullWidth ? 'flex-1' : ''}">
			<Input
				id="session-setup-source-inline"
				class="h-8 {fullWidth ? 'w-full' : 'w-[320px]'} min-w-0 text-xs"
				value={sessionView.pendingWorkspaceSourceInput}
				placeholder={
					workspaceSourceType === "local"
						? "~/projects/my-app"
						: "https://github.com/org/repo or org/repo"
				}
				onfocus={handleWorkspaceSourceFocus}
				onblur={handleWorkspaceSourceBlur}
				oninput={(event) => {
					handleWorkspaceSourceInputChange((event.currentTarget as HTMLInputElement).value);
				}}
				onkeydown={handleSourceKeydown}
			/>

			{#if showWorkspaceSuggestions && workspaceSuggestions.length > 0}
				<div class="absolute right-0 top-full z-50 mt-1 max-h-56 {fullWidth ? 'w-full' : 'w-[320px]'} overflow-y-auto rounded-md border border-border bg-popover shadow-lg">
					{#each workspaceSuggestions as suggestion, index (suggestion.value)}
						<button
							type="button"
							class={`flex w-full items-center justify-between gap-2 px-3 py-2 text-left text-xs hover:bg-accent ${index === selectedWorkspaceSuggestionIndex ? "bg-accent" : ""} ${suggestion.valid ? "" : "opacity-70"}`}
							onmouseenter={() => {
								selectedWorkspaceSuggestionIndex = index;
							}}
							onmousedown={(event) => {
								event.preventDefault();
								applyWorkspaceSuggestion(suggestion.value);
							}}
						>
							<span class="truncate font-mono">{suggestion.value}</span>
							{#if suggestion.valid}
								<CheckIcon class="size-3.5 text-primary" />
							{/if}
						</button>
					{/each}
				</div>
			{/if}
		</div>
	{:else}
		<NativeSelect
			id="session-setup-workspace-inline"
			ref={workspaceSelectRef}
			class="h-8 {fullWidth ? 'w-full' : 'w-[320px]'} min-w-0 text-xs"
			value={sessionView.pendingWorkspaceOption}
			disabled={loadingWorkspaces}
			onchange={(event) => {
				handleWorkspaceOptionChange((event.currentTarget as HTMLSelectElement).value);
			}}
		>
			{#if availableWorkspaces.length > 0}
				<optgroup label="Existing workspaces">
					{#each availableWorkspaces as workspace (workspace.id)}
						<option value={`existing:${workspace.id}`}>
							{getWorkspaceOptionLabel(workspace)}
						</option>
					{/each}
				</optgroup>
			{/if}
			<optgroup label="Create new">
				<option value="new-workspace">Empty Workspace</option>
				<option value="local-directory">Local Directory</option>
				<option value="git-repo">GitHub Repo</option>
			</optgroup>
		</NativeSelect>
	{/if}
</div>

{#if showBranchSelector}
	<DropdownMenu>
		<DropdownMenuTrigger class="tauri-no-drag">
			<InputGroupButton
				type="button"
				size="icon-sm"
				variant="ghost"
				aria-label="Select branch"
				title={sessionView.pendingWorkspaceBranch || "No branch selected"}
			>
				<GitBranchIcon
					class={`size-4 ${sessionView.pendingWorkspaceBranch ? "text-foreground" : "text-muted-foreground"}`}
				/>
			</InputGroupButton>
		</DropdownMenuTrigger>
		<DropdownMenuContent align="end" class="w-56">
			<DropdownMenuItem
				onclick={() => {
					sessionView.setPendingWorkspaceBranch("");
				}}
				class="justify-between"
			>
				<span>No branch</span>
				{#if sessionView.pendingWorkspaceBranch === ""}
					<CheckIcon class="size-3.5 text-primary" />
				{/if}
			</DropdownMenuItem>
			<DropdownMenuSeparator />
			{#each availableWorkspaceBranches as branch (branch)}
				<DropdownMenuItem
					onclick={() => {
						sessionView.setPendingWorkspaceBranch(branch);
					}}
					class="justify-between"
				>
					<span class="truncate">{branch}</span>
					{#if sessionView.pendingWorkspaceBranch === branch}
						<CheckIcon class="size-3.5 text-primary" />
					{/if}
				</DropdownMenuItem>
			{/each}
		</DropdownMenuContent>
	</DropdownMenu>
{/if}
