// API Types - shared between client and server

import type {
	SessionStatus as SessionStatusConstants,
	WorkspaceStatus as WorkspaceStatusConstants,
} from "./api-constants";
import type { UIMessage } from "ai";

export type ThreadState = "interrupted" | "cancelled";

export interface Thread {
	id: string;
	name: string;
	lastMessage?: string;
	errorMessage?: string;
	model?: string;
	reasoning?: string;
	mode: string;
	state?: ThreadState;
	activeCommand?: string; // empty or omitted when no command is running
	pending?: boolean;
	promptQueue?: QueuedPrompt[];
}

export type QueuedPromptMessagePart =
	| {
			type: "text";
			text: string;
	  }
	| {
			type: "file";
			filename?: string;
			mediaType?: string;
			url: string;
	  };

export interface QueuedPromptMessage {
	id: string;
	role: string;
	parts: QueuedPromptMessagePart[];
	metadata?: Record<string, unknown>;
}

export interface QueuedPrompt {
	id: string;
	createdAt?: string;
	message: QueuedPromptMessage;
	model?: string;
	reasoning?: string;
	mode?: string;
}

export type ChatSlashCommandMetadata = {
	name?: string;
	kind?: "skill" | "command" | "script";
	text?: string;
	script?: {
		scriptName?: string;
		scriptPath?: string;
		exitCode?: number;
		success?: boolean;
		stdout?: string;
		stderr?: string;
		suppressedLlm?: boolean;
	};
};

export type ChatMessageMetadata = {
	model?: string;
	reasoning?: string;
	originalText?: string;
	slashCommand?: ChatSlashCommandMetadata;
} & Record<string, unknown>;

export type ChatMessageDataTypes = {
	"thread-update": {
		thread: Thread;
	};
	"thread-resume": {
		threadId?: string;
		messageId?: string;
	};
	"completion-status": {
		threadId?: string;
		completionId?: string;
		isRunning?: boolean;
	};
	"retry-status": {
		message?: string;
	};
	"user-message": {
		insertBeforeMessageId?: string;
		message: ChatMessage;
	};
	"tool-approval-response": {
		approvalId?: string;
		approved?: boolean;
		reason?: string;
	};
	"hooks-status": HooksStatusResponse;
};

/** User preference key-value pair */
export interface UserPreference {
	key: string;
	value: string;
	updatedAt?: string;
}

/** File status in diff */
export type FileStatus = "added" | "modified" | "deleted" | "renamed";

/** Theme color scheme for customization */
export type ThemeColorScheme =
	| "default"
	| "flexoki"
	| "nord"
	| "tokyo-night"
	| "solarized"
	| "dracula"
	| "alucard"
	| "catppuccin-mocha"
	| "catppuccin-macchiato"
	| "catppuccin-frappe"
	| "catppuccin-latte";

export interface FileNode {
	id: string;
	name: string;
	type: "file" | "folder";
	children?: FileNode[];
	content?: string;
	originalContent?: string;
	changed?: boolean;
	/** File status: added, modified, deleted, or renamed */
	status?: FileStatus;
}

// Session status values representing the lifecycle of a session
export type SessionStatus =
	(typeof SessionStatusConstants)[keyof typeof SessionStatusConstants];

// Commit operation values representing which operation owns local UI state
export type CommitOperation = "commit" | "rebase";

export interface Session {
	id: string;
	name: string;
	/** Optional display name for the session (if not set, name is used) */
	displayName?: string;
	description: string;
	createdAt: string;
	timestamp: string;
	status: SessionStatus;
	/** Workspace commit SHA when commit started (expected parent) */
	baseCommit?: string;
	/** Final commit SHA after patches applied to workspace */
	appliedCommit?: string;
	/** Error message if status is "error" */
	errorMessage?: string;
	files: FileNode[];
	workspaceId?: string;
	model?: string;
	reasoning?: string;
	/** Permission mode: "plan" for planning mode, or "build" for normal execution */
	mode?: string;
}

// Workspace status values representing the lifecycle of a workspace
export type WorkspaceStatus =
	(typeof WorkspaceStatusConstants)[keyof typeof WorkspaceStatusConstants];

export interface ProviderStatus {
	available: boolean;
	state: "ready" | "downloading" | "failed" | "not_available";
	message?: string;
	details?: unknown;
}

export interface ProvidersResponse {
	providers: Record<string, ProviderStatus>;
	default: string;
}

export interface Workspace {
	id: string;
	path: string;
	/** Optional display name for the workspace (if not set, path is used) */
	displayName?: string;
	sourceType: "local" | "git" | "managed";
	/** Sandbox provider (empty string = use platform default) */
	provider?: string;
	/** True when workspace was auto-created for a session without explicit workspace selection */
	autoGenerated?: boolean;
	status: WorkspaceStatus;
	/** Error message if status is "error" */
	errorMessage?: string;
	/** Current commit SHA (if git workspace) */
	commit?: string;
	/** Working directory path on disk (if initialized) */
	workDir?: string;
}

export interface ProjectVMResources {
	cpuCount: number;
	memoryMB: number;
	dataDiskGB: number;
	canIncreaseDisk: boolean;
	canDecreaseDisk: boolean;
	canChangeMemory: boolean;
	restartRequiredForDisk: boolean;
	restartRequiredForMemory: boolean;
}

export interface ProjectResources {
	provider: string;
	vm: ProjectVMResources;
}

export interface UpdateProjectResourcesRequest {
	memoryMB?: number;
	dataDiskGB?: number;
}

export interface ProjectResourcesUpdateResult {
	provider: string;
	previous: ProjectVMResources;
	current: ProjectVMResources;
	restartRequired: boolean;
}

export interface ProjectInspectionInfo {
	provider: string;
	available: boolean;
	containerName: string;
	scope: "host" | "project_vm" | string;
}

export interface Badge {
	label: string;
	className: string;
}

export type ProviderCategory = "llm" | "vcs";

export interface AuthProvider {
	id: string;
	name: string;
	configuredName?: string;
	description?: string;
	secretLabel?: string;
	secretDescription?: string;
	autoGenerateSecret?: boolean;
	autoGeneratePrefix?: string;
	autoGenerateDescription?: string;
	icons?: Icon[];
	env?: string[]; // Environment variable names for API keys
	category: ProviderCategory;
}

export type CredentialTypeGroup =
	| "model-providers"
	| "git-version-control"
	| "tools";

export type CredentialOAuthKind = "authorization_code" | "device_code";

export interface CredentialTypeOAuthScopeOption {
	value: string;
	label: string;
	description?: string;
	group?: string;
	access?: string;
	includeInSimple?: boolean;
	simpleLabel?: string;
	simpleHelpText?: string;
}

export interface CredentialTypeOAuthConfig {
	provider: string;
	kind: CredentialOAuthKind;
	supportedKinds?: CredentialOAuthKind[];
	description?: string;
	inputLabel?: string;
	inputPlaceholder?: string;
	allowsDirectToken?: boolean;
	defaultScopes?: string[];
	scopeOptions?: CredentialTypeOAuthScopeOption[];
}

export interface CredentialType {
	id: string;
	provider: string;
	backendProvider: string;
	name: string;
	configuredName?: string;
	description?: string;
	secretLabel?: string;
	secretDescription?: string;
	autoGenerateSecret?: boolean;
	autoGeneratePrefix?: string;
	autoGenerateDescription?: string;
	icons?: Icon[];
	env?: string[];
	category: ProviderCategory;
	group: CredentialTypeGroup;
	groupName: string;
	authType: CredentialAuthType;
	oauth?: CredentialTypeOAuthConfig;
}

export interface AgentCommandApprovedUse {
	description: string;
}

export interface AgentCommandCredentialRequest {
	envVar: string;
	name: string;
	justification: string;
	approvedUses?: AgentCommandApprovedUse[];
}

export interface AgentCommandDiscobotMetadata {
	ui?: boolean;
	label?: string;
	activeLabel?: string;
	icon?: string;
	group?: string;
	order?: number;
	credentialRequest?: AgentCommandCredentialRequest[];
}

export interface AgentCommand {
	name: string;
	description: string;
	kind: string;
	discobot?: AgentCommandDiscobotMetadata;
}

export interface ModelInfo {
	id: string;
	name: string;
	provider?: string;
	description?: string;
	/** Whether this model supports extended thinking/reasoning */
	reasoning?: boolean;
	reasoningLevels?: string[];
	defaultReasoning?: string;
}

export interface ModelsResponse {
	models: ModelInfo[];
}

// ChatMessage extends the AI SDK UIMessage with local-only UI state.
export type ChatMessage = UIMessage<
	ChatMessageMetadata,
	ChatMessageDataTypes
> & {
	provisional?: boolean;
	status?: "streaming";
};

export interface Suggestion {
	value: string;
	type: "path" | "repo";
	valid: boolean;
	classification?: string;
}

export type WorkspaceValidationClassification =
	| "new"
	| "empty"
	| "existing_git"
	| "cloneable"
	| "invalid";

export interface ValidateWorkspaceRequest {
	path: string;
	sourceType: "local" | "git";
}

export interface WorkspaceValidationResult {
	path: string;
	sourceType: "local" | "git";
	valid: boolean;
	classification: WorkspaceValidationClassification;
	error?: string;
	suggestions: Suggestion[];
	authProvider?: string;
	authRequired?: boolean;
	authMessage?: string;
}

// API Request/Response types
export interface CreateWorkspaceRequest {
	path: string;
	displayName?: string;
	sourceType: "local" | "git";
	provider?: string;
}

export interface CreateSessionRequest {
	name: string;
	/** Initial message to start the chat session with */
	initialMessage?: string;
}

export interface UpdateSessionRequest {
	name?: string;
	displayName?: string | null;
	status?: SessionStatus;
}

export interface TerminalExecuteRequest {
	command: string;
	sessionId?: string;
}

export interface TerminalExecuteResponse {
	output: string;
	exitCode: number;
}

export interface TerminalMessage {
	type: "input" | "output" | "resize";
	data?: string;
	cols?: number;
	rows?: number;
}

export interface Icon {
	/**
	 * A standard URI pointing to an icon resource. May be an HTTP/HTTPS URL or a
	 * `data:` URI with Base64-encoded image data.
	 */
	src: string;
	/**
	 * Optional MIME type override if the source MIME type is missing or generic.
	 */
	mimeType?: string;
	/**
	 * Optional array of strings that specify sizes at which the icon can be used.
	 * Each string should be in WxH format (e.g., "48x48", "96x96") or "any" for scalable formats like SVG.
	 */
	sizes?: string[];
	/**
	 * Optional specifier for the theme this icon is designed for.
	 */
	theme?: "light" | "dark";
	/**
	 * If true, invert colors for dark mode (for black-on-white icons).
	 */
	invertDark?: boolean;
}

export interface Icons {
	/**
	 * Optional set of sized icons that the client can display in a user interface.
	 */
	icons?: Icon[];
}

export type CredentialAuthType = "api_key" | "id" | "oauth";

export interface CredentialEnvVar {
	key: string;
	value: string;
}

export interface OAuthData {
	access?: string;
	refresh?: string;
	expires?: number;
}

export interface Credential {
	id: string;
	name: string;
	provider: string;
	authType: CredentialAuthType;
	/** API key for api_key auth type (stored server-side, not returned to client) */
	apiKey?: string;
	/** OAuth tokens for oauth auth type (stored server-side, not returned to client) */
	oauthData?: OAuthData;
	/** Whether the credential is configured */
	isConfigured: boolean;
	/** When the credential was last updated */
	updatedAt?: string;
}

/** Client-safe credential (no secrets) */
export interface CredentialVisibility {
	tools: boolean;
	console: boolean;
	services: boolean;
	hooks: boolean;
}

export interface CredentialInfo {
	id: string;
	name: string;
	provider: string;
	description?: string;
	authType: CredentialAuthType;
	isConfigured: boolean;
	inactive: boolean;
	agentVisible: boolean;
	visibility: CredentialVisibility;
	envKeys?: string[];
	envVars?: CredentialEnvVar[];
	scopes?: string[];
	expiresAt?: string; // For OAuth credentials
	updatedAt?: string;
}

export interface CreateCredentialRequest {
	provider?: string;
	credentialId?: string;
	name: string;
	description?: string;
	authType: CredentialAuthType;
	apiKey?: string;
	envVars?: CredentialEnvVar[];
	agentVisible?: boolean;
	visibility?: CredentialVisibility;
	inactive?: boolean;
	oauthData?: OAuthData;
}

export interface SessionCredentialAssignment {
	credentialId: string;
	sessionCredentialId?: string;
	envVar?: string;
	sourceEnvVar?: string;
	agentVisible: boolean;
	visibility: CredentialVisibility;
	uses?: SessionCredentialUse[];
	credential: CredentialInfo;
}

export interface SessionCredentialUse {
	id: string;
	description: string;
	createdAt?: string;
	expiresAt?: string;
	lastUsedAt?: string;
	lastUsedToolCallId?: string;
}

export interface SetSessionCredentialsRequest {
	credentials: Array<{
		credentialId: string;
		sessionCredentialId?: string;
		envVar?: string;
		sourceEnvVar?: string;
		agentVisible: boolean;
		visibility?: CredentialVisibility;
		uses?: SessionCredentialUse[];
	}>;
}

export interface OAuthExchangeRequest {
	code: string;
	verifier: string;
}

export interface OAuthExchangeResponse {
	success: boolean;
	error?: string;
}

export interface OAuthAuthorizeResponse {
	url: string;
	verifier: string;
}

export interface OAuthRefreshResponse {
	success: boolean;
	expiresAt?: string;
	expiresIn?: number;
}

// GitHub Copilot OAuth types
export interface GitHubCopilotDeviceCodeRequest {
	deploymentType?: "github.com" | "enterprise";
	enterpriseUrl?: string;
}

export interface GitHubCopilotDeviceCodeResponse {
	verificationUri: string;
	userCode: string;
	deviceCode: string;
	interval: number;
	expiresIn: number;
	domain: string;
}

export interface GitHubCopilotPollRequest {
	deviceCode: string;
	domain: string;
}

export interface GitHubCopilotPollResponse {
	status: "pending" | "success" | "error";
	error?: string;
}

// GitHub OAuth types (git operations: repo scope)
export interface GitHubAuthorizeRequest {
	enterpriseUrl?: string;
	redirectUri?: string;
	scopes?: string[];
	credentialId?: string;
	name?: string;
	description?: string;
	visibility?: CredentialVisibility;
	inactive?: boolean;
}

export interface GitHubAuthorizeResponse {
	url: string;
	verifier: string;
	state: string;
	redirectUri: string;
	callbackListening: boolean;
}

export interface GitHubDeviceCodeRequest {
	enterpriseUrl?: string;
	scopes?: string[];
}

export interface GitHubDeviceCodeResponse {
	verificationUri: string;
	userCode: string;
	deviceCode: string;
	interval: number;
	expiresIn: number;
	domain: string;
}

export interface GitHubPollRequest {
	deviceCode: string;
	domain: string;
	credentialId?: string;
	name?: string;
	description?: string;
	visibility?: CredentialVisibility;
	inactive?: boolean;
}

export interface GitHubPollResponse {
	status: "pending" | "success" | "error";
	error?: string;
}

export interface GitHubExchangeRequest {
	code: string;
	redirectUri?: string;
	verifier: string;
	enterpriseUrl?: string;
	credentialId?: string;
	name?: string;
	description?: string;
	visibility?: CredentialVisibility;
	inactive?: boolean;
}

export interface GitHubExchangeResponse {
	success: boolean;
	error?: string;
}

export interface GitHubCallbackStatusRequest {
	state: string;
}

export interface GitHubCallbackStatusResponse {
	status: "pending" | "success" | "error";
	error?: string;
}

// Codex (ChatGPT) OAuth types
export interface CodexAuthorizeResponse {
	url: string;
	verifier: string;
	state: string;
	redirectUri: string;
	callbackListening: boolean;
}

export interface CodexExchangeRequest {
	code: string;
	redirectUri?: string;
	verifier: string;
}

export interface CodexExchangeResponse {
	success: boolean;
	error?: string;
}

export interface CodexDeviceCodeResponse {
	deviceAuthId: string;
	userCode: string;
	verificationUri: string;
	interval: number;
}

export interface CodexPollRequest {
	deviceAuthId: string;
	userCode: string;
}

export interface CodexPollResponse {
	status: "pending" | "success" | "error";
	error?: string;
	accountId?: string;
}

export interface CodexCallbackStatusRequest {
	state: string;
}

export interface CodexCallbackStatusResponse {
	status: "pending" | "success" | "error";
	error?: string;
}

// System Status types
export type StatusMessageLevel = "warn" | "error";

export interface StatusMessage {
	id: string;
	level: StatusMessageLevel;
	title: string;
	message: string;
}

export interface AuthUser {
	id: string;
	email: string;
	name: string;
	avatarUrl?: string;
	provider: string;
}

export interface ServerConfig {
	ssh_port: number;
	http_port?: number;
	https_port?: number;
	https_tls_mode?: "ephemeral" | "static" | "acme";
	public_base_url: string;
}

export interface SystemStatusResponse {
	ok: boolean;
	messages: StatusMessage[];
	startupTasks?: StartupTask[];
}

// Startup Task types
export type StartupTaskState =
	| "pending"
	| "in_progress"
	| "completed"
	| "failed";

export interface StartupTask {
	id: string;
	name: string;
	state: StartupTaskState;
	/** Progress percentage (0-100) */
	progress?: number;
	/** Current operation description */
	currentOperation?: string;
	/** Bytes downloaded (for download tasks) */
	bytesDownloaded?: number;
	/** Total bytes (for download tasks) */
	totalBytes?: number;
	/** Error message if state is "failed" */
	error?: string;
	/** When the task started */
	startedAt?: string;
	/** When the task completed or failed */
	completedAt?: string;
}

/** Runtime information for debug/support */
export interface RuntimeInfo {
	os: string;
	arch: string;
	go_version: string;
	num_cpu: number;
	num_goroutine: number;
}

/** Disk usage information */
export interface DiskUsageInfo {
	total_bytes: number;
	used_bytes: number;
	available_bytes: number;
	used_percent: number;
}

/** Size information for a sparse data disk file */
export interface DataDiskFileInfo {
	path: string;
	apparent_bytes: number;
	actual_bytes: number;
}

/** VZ-specific configuration and disk usage */
export interface VZInfo {
	image_ref: string;
	data_dir: string;
	cpu_count: number;
	memory_mb: number;
	data_disk_gb: number;
	disk_usage?: DiskUsageInfo;
	data_disks?: DataDiskFileInfo[];
	kernel_path?: string;
	initrd_path?: string;
	base_disk_path?: string;
}

/** Configuration information for debug/support (sanitized, no secrets) */
export interface ConfigInfo {
	port: number;
	https_port?: number;
	https_tls_mode?: "ephemeral" | "static" | "acme";
	database_driver: string;
	auth_enabled: boolean;
	workspace_dir: string;
	sandbox_image: string;
	desktop_mode: boolean;
	desktop_runtime?: "tauri" | "electron";
	tauri_mode: boolean;
	ssh_enabled: boolean;
	ssh_port: number;
	dispatcher_enabled: boolean;
	available_providers: string[];
	vz?: VZInfo;
}

/** Support information response with diagnostic data */
export interface SupportInfoResponse {
	version: string;
	runtime: RuntimeInfo;
	config: ConfigInfo;
	server_log: string;
	log_path: string;
	log_exists: boolean;
	system_info: SystemStatusResponse;
}

/** Response from cancelling a chat completion */
export interface CancelChatResponse {
	success: boolean;
	completionId: string;
	status: "cancelled";
}

export interface ListThreadsResponse {
	threads: Thread[];
}

export interface CreateThreadRequest {
	id: string;
	name?: string;
}

export interface UpdateThreadRequest {
	name?: string;
}

export interface DeleteThreadResponse {
	success: boolean;
}

export interface DeleteQueuedPromptResponse {
	success: boolean;
}

export interface StartChatRequest {
	id?: string;
	sessionId: string;
	threadId: string;
	messages: UIMessage[];
	workspaceId?: string;
	model?: string;
	reasoning?: string;
	mode?: string;
	trigger?: string;
	messageId?: string;
}

export interface StartChatResponse {
	workspaceId: string;
	sessionId: string;
	threadId: string;
	messageId?: string;
	completionId?: string;
	status?: "started" | "queued";
	queuedPromptId?: string;
}

export interface StartChatConflictResponse {
	error: "completion_in_progress";
	completionId: string;
}

export interface StartChatTurnStateConflictResponse {
	error:
		| "interrupted_turn_requires_resume"
		| "pending_question_requires_answer";
	message?: string;
	questionId?: string;
	completionId?: string;
}

export type StartChatErrorResponse =
	| StartChatConflictResponse
	| StartChatTurnStateConflictResponse;

export type ChatStreamSocketEventName =
	| "history-start"
	| "history-message"
	| "history-end"
	| "chunk"
	| "ping";

export type ProjectStreamType = "chat" | "service" | "project-events";

export type ProjectStreamSocketRequest =
	| {
			type: "subscribe" | "unsubscribe";
			stream: "chat";
			sessionId: string;
			threadId: string;
			replay?: boolean;
			lastEventId?: string;
	  }
	| {
			type: "subscribe" | "unsubscribe";
			stream: "service";
			sessionId: string;
			serviceId: string;
	  }
	| {
			type: "subscribe" | "unsubscribe";
			stream: "project-events";
			afterId?: string;
	  };

export type ProjectStreamSocketMessage = {
	type: "subscribed" | "event" | "complete" | "error" | "unsubscribed";
	stream?: ProjectStreamType;
	sessionId?: string;
	threadId?: string;
	serviceId?: string;
	event?: string;
	data?: string;
	id?: string;
	error?: string;
	replay?: boolean;
};

export type ProjectStreamSubscriptionState =
	| "idle"
	| "subscribing"
	| "streaming";

// ============================================================================
// Session File System Types
// ============================================================================

/** File entry in a directory listing */
export interface SessionFileEntry {
	name: string;
	type: "file" | "directory";
	size?: number;
}

/** Response from listing session files */
export interface ListSessionFilesResponse {
	path: string;
	entries: SessionFileEntry[];
}

/** Single result from a fuzzy file search */
export interface SearchFileEntry {
	path: string;
	type: "file" | "directory";
	score: number;
}

/** Response from searching session workspace files */
export interface SearchSessionFilesResponse {
	query: string;
	results: SearchFileEntry[];
}

/** Response from reading a session file */
export interface ReadSessionFileResponse {
	path: string;
	content: string;
	encoding: "utf8" | "base64";
	size: number;
}

/** Request to write a session file */
export interface WriteSessionFileRequest {
	path: string;
	content: string;
	encoding?: "utf8" | "base64";
	/** Original content for optimistic locking - if provided, server validates before write */
	originalContent?: string;
}

/** Response from writing a session file */
export interface WriteSessionFileResponse {
	path: string;
	size: number;
}

/** Request to delete a session file or directory */
export interface DeleteSessionFileRequest {
	path: string;
}

/** Response from deleting a session file or directory */
export interface DeleteSessionFileResponse {
	path: string;
	type: "file" | "directory";
}

/** Request to rename/move a session file or directory */
export interface RenameSessionFileRequest {
	oldPath: string;
	newPath: string;
}

/** Response from renaming a session file or directory */
export interface RenameSessionFileResponse {
	oldPath: string;
	newPath: string;
}

/** Error response when file content has changed (optimistic locking conflict) */
export interface WriteSessionFileConflictError {
	error: "conflict";
	message: string;
	/** Current content on the server */
	currentContent: string;
}

/** Single file diff entry */
export interface SessionFileDiffEntry {
	path: string;
	status: "added" | "modified" | "deleted" | "renamed";
	oldPath?: string;
	additions: number;
	deletions: number;
	binary: boolean;
	patch?: string;
}

/** Diff statistics */
export interface SessionDiffStats {
	filesChanged: number;
	additions: number;
	deletions: number;
}

/** Full diff response */
export interface SessionDiffResponse {
	files: SessionFileDiffEntry[];
	stats: SessionDiffStats;
}

/** File entry with status for diff response */
export interface SessionDiffFileEntry {
	path: string;
	status: FileStatus;
	oldPath?: string; // For renamed files
}

/** Files-only diff response (with status) */
export interface SessionDiffFilesResponse {
	files: SessionDiffFileEntry[];
	stats: SessionDiffStats;
}

/** Single file diff response */
export interface SessionSingleFileDiffResponse {
	path: string;
	status: "added" | "modified" | "deleted" | "renamed" | "unchanged";
	oldPath?: string;
	additions: number;
	deletions: number;
	binary: boolean;
	patch: string;
}

// ============================================================================
// Service Types
// ============================================================================

/** Service status representing the lifecycle of a service */
export type ServiceStatus = "running" | "stopped" | "starting" | "stopping";

/** Service represents a user-defined service in the sandbox */
export interface Service {
	/** Filename in .discobot/services/ */
	id: string;
	/** Display name (from config or id) */
	name: string;
	/** Description from config */
	description?: string;
	/** Optional UI ordering hint (lower first) */
	order?: number;
	/** HTTP port if http service */
	http?: number;
	/** HTTPS port if https service */
	https?: number;
	/** Absolute path to service file */
	path: string;
	/** Default URL path for web preview (e.g., "/app") */
	urlPath?: string;
	/** Current status */
	status: ServiceStatus;
	/**
	 * Whether this is a passive service (external HTTP endpoint).
	 * Passive services are not started/stopped - they just declare an HTTP port.
	 */
	passive?: boolean;
	/** Process ID if running */
	pid?: number;
	/** ISO timestamp when started */
	startedAt?: string;
	/** Exit code if stopped after running */
	exitCode?: number;
}

/** Response from listing services */
export interface ListServicesResponse {
	services: Service[];
}

/** Response from starting a service */
export interface StartServiceResponse {
	status: "starting";
	serviceId: string;
}

/** Response from stopping a service */
export interface StopServiceResponse {
	status: "stopped";
	serviceId: string;
}

/** Service output event from the realtime stream */
export interface ServiceOutputEvent {
	type: "stdout" | "stderr" | "exit" | "error";
	data?: string;
	exitCode?: number;
	error?: string;
	timestamp: string;
}

// ============================================================================
// AskUserQuestion Types
// ============================================================================

/** A single choice option for a clarifying question */
export interface AskUserQuestionOption {
	label: string;
	description: string;
}

/** A single clarifying question from Claude */
export interface AskUserQuestion {
	question: string;
	header: string;
	options: AskUserQuestionOption[];
	multiSelect: boolean;
	notes?: string;
}

export interface RequestedCredential {
	envVar: string;
	name: string;
	justification: string;
	approvedUses: RequestedCredentialApprovedUse[];
}

export interface RequestedCredentialApprovedUse {
	description: string;
}

export interface GrantedCredentialApprovedUse {
	id: string;
	description: string;
}

export interface GrantedCredential {
	credentialId: string;
	envVar: string;
	name: string;
	approvedUses: GrantedCredentialApprovedUse[];
}

/** A pending approval waiting for user answers */
export interface PendingQuestion {
	toolUseID: string;
	questions?: AskUserQuestion[];
	credentials?: RequestedCredential[];
	metadata?: Record<string, unknown>;
	context?: string;
}

/** Response from GET /sessions/{sessionId}/threads/{threadId}/question/{questionId} */
export interface PendingQuestionResponse {
	status: "pending" | "answered" | "expired";
	question: PendingQuestion | null;
}

export interface CommitPullPreviewStats {
	filesChanged: number;
	additions: number;
	deletions: number;
	lineCount: number;
}

export interface CommitPullPreviewFile {
	path: string;
	oldPath?: string;
	status: "added" | "modified" | "deleted" | "renamed";
	additions: number;
	deletions: number;
	lineCount: number;
	binary: boolean;
	patch?: string;
}

export interface CommitPullPreviewCommit {
	hash: string;
	subject: string;
	body?: string;
	authorName?: string;
	authorEmail?: string;
	date?: string;
	signedOffBy?: string[];
	stats: CommitPullPreviewStats;
	files: CommitPullPreviewFile[];
}

export interface CommitPullPreviewResponse {
	commitCount: number;
	headCommit: string;
	rawPatch: string;
	stats: CommitPullPreviewStats;
	commits: CommitPullPreviewCommit[];
}

/** Request body for POST /sessions/{sessionId}/threads/{threadId}/answer/{questionId} */
export interface AnswerQuestionRequest {
	toolUseID: string;
	answers?: Record<string, string>;
	credentials?: Record<string, string>;
}

/** Response from POST /sessions/{sessionId}/threads/{threadId}/answer/{questionId} */
export interface AnswerQuestionResponse {
	success: boolean;
}

// ============================================================================
// Hook Types
// ============================================================================

/** Status of a single hook's runs */
export interface HookRunStatus {
	hookId: string;
	hookName: string;
	type: "session" | "file" | "pre-commit";
	lastRunAt: string;
	lastResult: "success" | "failure" | "running" | "pending";
	lastExitCode: number;
	outputPath: string;
	runCount: number;
	failCount: number;
	consecutiveFailures: number;
}

/** Hook evaluation status for a session */
export interface HooksStatusResponse {
	hooks: Record<string, HookRunStatus>;
	pendingHooks: string[];
	lastEvaluatedAt: string;
}

/** Hook output log response */
export interface HookOutputResponse {
	output: string;
	sizeBytes: number;
	displayedBytes: number;
	tooLarge: boolean;
}

/** Hook rerun response */
export interface HookRerunResponse {
	success: boolean;
	exitCode: number;
}

// ============================================================================
// UI Types
// ============================================================================

/** Active view type in the session view - includes chat, terminal, services, file paths, and consolidated diff */
export type ActiveView =
	| "chat"
	| "terminal"
	| "desktop"
	| "consolidated-diff"
	| `service:${string}`
	| `file:${string}`;
