package hooks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const managedMarker = "# discobot:managed"

// InstallPreCommitHook generates and installs a git pre-commit hook script
// that chains any existing pre-commit hook and runs all pre-commit type hooks.
func InstallPreCommitHook(workspaceRoot string, preCommitHooks []Hook, sessionID string) error {
	hookPath := filepath.Join(workspaceRoot, ".git", "hooks", "pre-commit")

	// Check for existing pre-commit hook
	existing, err := os.ReadFile(hookPath)
	if err == nil {
		if !strings.Contains(string(existing), managedMarker) {
			// Not ours — preserve it as .pre-commit.original
			origPath := filepath.Join(workspaceRoot, ".git", "hooks", "pre-commit.original")
			if err := os.WriteFile(origPath, existing, 0o755); err != nil {
				return fmt.Errorf("preserve existing pre-commit hook: %w", err)
			}
		}
		// If it contains our marker, we'll overwrite it
	}

	script := generatePreCommitScript(preCommitHooks, sessionID)

	_ = os.MkdirAll(filepath.Dir(hookPath), 0o755)
	if err := os.WriteFile(hookPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write pre-commit hook: %w", err)
	}

	return nil
}

// generatePreCommitScript builds the pre-commit hook bash script.
func generatePreCommitScript(hooks []Hook, sessionID string) string {
	var b strings.Builder

	b.WriteString(`#!/bin/bash
# Auto-generated by discobot hooks system
# Source: .discobot/hooks/
# DO NOT EDIT — regenerated when hooks change
`)
	b.WriteString(managedMarker)
	b.WriteString("\n\n")

	// Chain original hook if preserved
	b.WriteString(`# Chain original hook if preserved
if [ -f "$(dirname "$0")/pre-commit.original" ]; then
  "$(dirname "$0")/pre-commit.original" || exit $?
fi

`)

	// Status tracking setup
	b.WriteString(fmt.Sprintf(`# Status tracking setup
HOOKS_DATA_DIR="${HOME}/.discobot/threads/%s/hooks"
mkdir -p "$HOOKS_DATA_DIR/output"

`, sessionID))

	// update_hook_status function
	b.WriteString(`# Update hook status in status.json
update_hook_status() {
  local hook_id="$1"
  local hook_name="$2"
  local success="$3"
  local exit_code="$4"
  local output_path="$5"
  local status_file="$HOOKS_DATA_DIR/status.json"
  local tmp_file="$status_file.tmp.$$"

  # Determine result string
  local result="failure"
  if [ "$success" = "true" ]; then
    result="success"
  fi

  # Use node or bun to update status.json atomically
  local runtime=""
  if command -v node &>/dev/null; then
    runtime="node"
  elif command -v bun &>/dev/null; then
    runtime="bun"
  else
    return 0
  fi

  $runtime -e "
    const fs = require('fs');
    const statusFile = '$status_file';
    const tmpFile = '$tmp_file';
    let status = {hooks:{},pendingHooks:[],lastEvaluatedAt:''};
    try { status = JSON.parse(fs.readFileSync(statusFile,'utf8')); } catch {}
    if (!status.hooks) status.hooks = {};
    if (!status.pendingHooks) status.pendingHooks = [];
    const existing = status.hooks['$hook_id'] || {hookId:'$hook_id',hookName:'$hook_name',type:'pre-commit',runCount:0,failCount:0,consecutiveFailures:0};
    existing.lastRunAt = new Date().toISOString();
    existing.lastResult = '$result';
    existing.lastExitCode = $exit_code;
    existing.outputPath = '$output_path';
    existing.runCount = (existing.runCount||0) + 1;
    if ('$result' === 'failure') { existing.failCount = (existing.failCount||0) + 1; existing.consecutiveFailures = (existing.consecutiveFailures||0) + 1; }
    else { existing.consecutiveFailures = 0; }
    status.hooks['$hook_id'] = existing;
    fs.writeFileSync(tmpFile, JSON.stringify(status, null, '\t'));
    fs.renameSync(tmpFile, statusFile);
  " 2>/dev/null
}

`)

	// run_hook function
	b.WriteString(`# Run a single hook
run_hook() {
  local hook_path="$1"
  local hook_id="$2"
  local hook_name="$3"
  local output_path="$HOOKS_DATA_DIR/output/${hook_id}.log"

  output=$("$hook_path" 2>&1)
  local exit_code=$?

  # Save output regardless
  echo "$output" > "$output_path"

  if [ $exit_code -ne 0 ]; then
    echo "$output" >&2
    update_hook_status "$hook_id" "$hook_name" "false" "$exit_code" "$output_path"
    exit $exit_code
  fi

  update_hook_status "$hook_id" "$hook_name" "true" "0" "$output_path"
}

`)

	// Run each hook
	for _, hook := range hooks {
		b.WriteString(fmt.Sprintf("run_hook %q %q %q\n", hook.Path, hook.ID, hook.Name))
	}

	return b.String()
}
