package providers

// CredentialTypeGroup groups credential choices in the UI.
type CredentialTypeGroup string

const (
	CredentialTypeGroupModelProviders CredentialTypeGroup = "model-providers"
	CredentialTypeGroupGitVersion     CredentialTypeGroup = "git-version-control"
	CredentialTypeGroupTools          CredentialTypeGroup = "tools"
)

// OAuthKind describes the interaction style for an OAuth flow.
type OAuthKind string

const (
	OAuthKindAuthorizationCode OAuthKind = "authorization_code"
	OAuthKindDeviceCode        OAuthKind = "device_code"
)

// OAuthConfig describes how the UI should drive an OAuth credential flow.
type OAuthConfig struct {
	Provider          string    `json:"provider"`
	Kind              OAuthKind `json:"kind"`
	Description       string    `json:"description,omitempty"`
	InputLabel        string    `json:"inputLabel,omitempty"`
	InputPlaceholder  string    `json:"inputPlaceholder,omitempty"`
	AllowsDirectToken bool      `json:"allowsDirectToken,omitempty"`
}

// CredentialType describes a selectable credential option in the current UI.
type CredentialType struct {
	ID                      string              `json:"id"`
	Provider                string              `json:"provider"`
	BackendProvider         string              `json:"backendProvider"`
	Name                    string              `json:"name"`
	ConfiguredName          string              `json:"configuredName,omitempty"`
	Description             string              `json:"description,omitempty"`
	SecretLabel             string              `json:"secretLabel,omitempty"`
	SecretDescription       string              `json:"secretDescription,omitempty"`
	AutoGenerateSecret      bool                `json:"autoGenerateSecret,omitempty"`
	AutoGeneratePrefix      string              `json:"autoGeneratePrefix,omitempty"`
	AutoGenerateDescription string              `json:"autoGenerateDescription,omitempty"`
	Icons                   []Icon              `json:"icons,omitempty"`
	Env                     []string            `json:"env,omitempty"`
	Category                ProviderCategory    `json:"category"`
	Group                   CredentialTypeGroup `json:"group"`
	GroupName               string              `json:"groupName"`
	AuthType                string              `json:"authType"`
	OAuth                   *OAuthConfig        `json:"oauth,omitempty"`
}

type credentialTypeSpec struct {
	ID                string
	DisplayProviderID string
	BackendProviderID string
	EnvProviderID     string
	Group             CredentialTypeGroup
	GroupName         string
	AuthType          string
	OAuth             *OAuthConfig
}

var credentialTypeSpecs = []credentialTypeSpec{
	{
		ID:                "anthropic:api_key",
		DisplayProviderID: "anthropic",
		BackendProviderID: "anthropic",
		Group:             CredentialTypeGroupModelProviders,
		GroupName:         "Model Providers",
		AuthType:          "api_key",
	},
	{
		ID:                "anthropic:oauth",
		DisplayProviderID: "anthropic",
		BackendProviderID: "anthropic",
		EnvProviderID:     "anthropic",
		Group:             CredentialTypeGroupModelProviders,
		GroupName:         "Model Providers",
		AuthType:          "oauth",
		OAuth: &OAuthConfig{
			Provider:          "anthropic",
			Kind:              OAuthKindAuthorizationCode,
			Description:       "Use Claude login (or a direct token) to connect Anthropic.",
			InputLabel:        "Authorization code or token",
			InputPlaceholder:  "Paste code or sk-ant-oat0...",
			AllowsDirectToken: true,
		},
	},
	{
		ID:                "openai:api_key",
		DisplayProviderID: "openai",
		BackendProviderID: "openai",
		Group:             CredentialTypeGroupModelProviders,
		GroupName:         "Model Providers",
		AuthType:          "api_key",
	},
	{
		ID:                "openai:oauth",
		DisplayProviderID: "openai",
		BackendProviderID: "codex",
		EnvProviderID:     "codex",
		Group:             CredentialTypeGroupModelProviders,
		GroupName:         "Model Providers",
		AuthType:          "oauth",
		OAuth: &OAuthConfig{
			Provider:         "codex",
			Kind:             OAuthKindAuthorizationCode,
			Description:      "Use ChatGPT login (Codex OAuth) to connect OpenAI.",
			InputLabel:       "Authorization code or callback URL",
			InputPlaceholder: "Paste code or callback URL",
		},
	},
	{
		ID:                "github-git:oauth",
		DisplayProviderID: "github-git",
		BackendProviderID: "github-git",
		Group:             CredentialTypeGroupGitVersion,
		GroupName:         "Git / Version Control",
		AuthType:          "oauth",
		OAuth: &OAuthConfig{
			Provider:    "github-git",
			Kind:        OAuthKindDeviceCode,
			Description: "Use GitHub device flow to connect GitHub for git operations.",
		},
	},
	{
		ID:                "tavily:api_key",
		DisplayProviderID: "tavily",
		BackendProviderID: "tavily",
		Group:             CredentialTypeGroupTools,
		GroupName:         "Tools",
		AuthType:          "api_key",
	},
}

// GetCredentialTypes returns the credential choices used by the current UI.
func GetCredentialTypes() []CredentialType {
	loadProviders()

	result := make([]CredentialType, 0, len(credentialTypeSpecs))
	for _, spec := range credentialTypeSpecs {
		displayProvider := Get(spec.DisplayProviderID)
		if displayProvider == nil {
			continue
		}

		envProviderID := spec.EnvProviderID
		if envProviderID == "" {
			envProviderID = spec.BackendProviderID
		}
		envProvider := Get(envProviderID)

		ct := CredentialType{
			ID:                      spec.ID,
			Provider:                spec.DisplayProviderID,
			BackendProvider:         spec.BackendProviderID,
			Name:                    displayProvider.Name,
			ConfiguredName:          displayProvider.ConfiguredName,
			Description:             displayProvider.Description,
			SecretLabel:             displayProvider.SecretLabel,
			SecretDescription:       displayProvider.SecretDescription,
			AutoGenerateSecret:      displayProvider.AutoGenerateSecret,
			AutoGeneratePrefix:      displayProvider.AutoGeneratePrefix,
			AutoGenerateDescription: displayProvider.AutoGenerateDescription,
			Icons:                   append([]Icon(nil), displayProvider.Icons...),
			Category:                displayProvider.Category,
			Group:                   spec.Group,
			GroupName:               spec.GroupName,
			AuthType:                spec.AuthType,
			OAuth:                   spec.OAuth,
		}
		if envProvider != nil {
			ct.Env = append([]string(nil), envProvider.Env...)
		}
		result = append(result, ct)
	}

	return result
}
