package providers

import (
	"sort"
	"sync"

	"github.com/obot-platform/discobot/modelsdev"
)

// Icon represents an icon with theme support
type Icon struct {
	Src        string   `json:"src"`
	MimeType   string   `json:"mimeType,omitempty"`
	Sizes      []string `json:"sizes,omitempty"`
	Theme      string   `json:"theme,omitempty"`      // "light" or "dark"
	InvertDark bool     `json:"invertDark,omitempty"` // If true, invert colors for dark mode
}

// ProviderCategory classifies what a credential is used for.
type ProviderCategory string

const (
	// CategoryLLM is for AI model providers (API keys / OAuth tokens sent to LLM APIs).
	CategoryLLM ProviderCategory = "llm"
	// CategoryVCS is for version-control credentials (git clone, push, PRs).
	CategoryVCS ProviderCategory = "vcs"
)

// AuthProvider represents an auth provider option
type AuthProvider struct {
	ID                      string           `json:"id"`
	Name                    string           `json:"name"`
	ConfiguredName          string           `json:"configuredName,omitempty"`
	Description             string           `json:"description,omitempty"`
	SecretLabel             string           `json:"secretLabel,omitempty"`
	SecretDescription       string           `json:"secretDescription,omitempty"`
	AutoGenerateSecret      bool             `json:"autoGenerateSecret,omitempty"`
	AutoGeneratePrefix      string           `json:"autoGeneratePrefix,omitempty"`
	AutoGenerateDescription string           `json:"autoGenerateDescription,omitempty"`
	Icons                   []Icon           `json:"icons,omitempty"`
	Env                     []string         `json:"env,omitempty"` // Environment variable names for API keys
	Category                ProviderCategory `json:"category"`      // "llm" or "vcs"
}

// Cached auth providers
var (
	authProvidersOnce   sync.Once
	cachedAuthProviders []AuthProvider
	providerEnvMap      map[string][]string // provider ID -> env var names
)

// Custom auth providers not available in models.dev
var customAuthProviders = []AuthProvider{
	{
		ID:          "codex",
		Name:        "Codex",
		Description: "OpenAI Codex CLI authentication",
		Category:    CategoryLLM,
		Icons: []Icon{
			{Src: "https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg", MimeType: "image/svg+xml", InvertDark: true},
		},
		Env: []string{"CODEX_TOKEN"},
	},
	{
		ID:          "github-copilot",
		Name:        "GitHub Copilot",
		Description: "GitHub Copilot authentication",
		Category:    CategoryLLM,
		Icons: []Icon{
			{Src: "https://cdn.simpleicons.org/githubcopilot", MimeType: "image/svg+xml", InvertDark: true},
		},
		Env: []string{"GITHUB_TOKEN"},
	},
	{
		ID:          "github-git",
		Name:        "GitHub",
		Description: "GitHub authentication for cloning repos and creating PRs",
		Category:    CategoryVCS,
		Icons: []Icon{
			{Src: "https://cdn.simpleicons.org/github", MimeType: "image/svg+xml", InvertDark: true},
		},
		Env: []string{"GITHUB_TOKEN"},
	},
	{
		ID:                      "discobot",
		Name:                    "Discobot",
		ConfiguredName:          "Discobot ID",
		Description:             "Discobot hosted web tools for web search and web fetch",
		SecretLabel:             "Discobot ID",
		SecretDescription:       "Used to identify you for cloud services.",
		AutoGenerateSecret:      true,
		AutoGeneratePrefix:      "discobot_",
		AutoGenerateDescription: "A random ID will be generated automatically when you save.",
		Category:                CategoryLLM,
		Env:                     []string{"DISCOBOT_TOKEN"},
	},
	{
		ID:          "tavily",
		Name:        "Tavily",
		Description: "Tavily Search API for web search capabilities",
		Category:    CategoryLLM,
		Icons: []Icon{
			{Src: "https://tavily.com/favicon.ico", MimeType: "image/x-icon"},
		},
		Env: []string{"TAVILY_API_KEY"},
	},
}

// loadProviders loads auth providers from embedded models.dev data and custom providers
func loadProviders() {
	authProvidersOnce.Do(func() {
		providerEnvMap = make(map[string][]string)

		// Start with custom providers (not in models.dev)
		customIDs := make(map[string]bool)
		for _, p := range customAuthProviders {
			customIDs[p.ID] = true
			providerEnvMap[p.ID] = p.Env
		}
		cachedAuthProviders = append(cachedAuthProviders, customAuthProviders...)

		// Add providers from models.dev (skip any that are in custom list)
		for _, p := range modelsdev.AllProviders() {
			// Build env map for all providers
			if len(p.EnvVars) > 0 {
				if _, exists := providerEnvMap[p.ID]; !exists {
					providerEnvMap[p.ID] = p.EnvVars
				}
			}

			// Skip custom providers for the full provider list
			if customIDs[p.ID] {
				continue
			}

			description := p.Name + " API"
			if p.Doc != "" {
				description = p.Name + " API access"
			}
			cachedAuthProviders = append(cachedAuthProviders, AuthProvider{
				ID:          p.ID,
				Name:        p.Name,
				Description: description,
				Category:    CategoryLLM,
				Icons: []Icon{
					{
						Src:        "https://models.dev/logos/" + p.ID + ".svg",
						MimeType:   "image/svg+xml",
						InvertDark: true,
					},
				},
				Env: p.EnvVars,
			})
		}

		// Sort by name
		sort.Slice(cachedAuthProviders, func(i, j int) bool {
			return cachedAuthProviders[i].Name < cachedAuthProviders[j].Name
		})
	})
}

// GetAll returns all auth providers
func GetAll() []AuthProvider {
	loadProviders()
	return cachedAuthProviders
}

// GetEnvVars returns the environment variable names for a provider
func GetEnvVars(providerID string) []string {
	loadProviders()
	return providerEnvMap[providerID]
}

// Get returns a specific auth provider by ID, or nil if not found
func Get(providerID string) *AuthProvider {
	loadProviders()
	for i := range cachedAuthProviders {
		if cachedAuthProviders[i].ID == providerID {
			return &cachedAuthProviders[i]
		}
	}
	return nil
}
