package handler

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"path/filepath"
	"strings"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/obot-platform/discobot/server/internal/jobs"
	"github.com/obot-platform/discobot/server/internal/middleware"
	"github.com/obot-platform/discobot/server/internal/model"
	"github.com/obot-platform/discobot/server/internal/service"
)

type sessionResponse struct {
	ID              string             `json:"id"`
	ProjectID       string             `json:"projectId"`
	Name            string             `json:"name"`
	DisplayName     string             `json:"displayName,omitempty"`
	Description     string             `json:"description"`
	CreatedAt       string             `json:"createdAt"`
	Timestamp       string             `json:"timestamp"`
	Status          string             `json:"status"`
	BaseCommit      string             `json:"baseCommit,omitempty"`
	AppliedCommit   string             `json:"appliedCommit,omitempty"`
	ErrorMessage    string             `json:"errorMessage,omitempty"`
	Files           []service.FileNode `json:"files"`
	WorkspaceID     string             `json:"workspaceId,omitempty"`
	WorkspacePath   string             `json:"workspacePath,omitempty"`
	WorkspaceCommit string             `json:"workspaceCommit,omitempty"`
}

type workspaceResponse struct {
	ID            string             `json:"id"`
	Path          string             `json:"path"`
	DisplayName   *string            `json:"displayName,omitempty"`
	SourceType    string             `json:"sourceType"`
	Provider      string             `json:"provider,omitempty"`
	AutoGenerated bool               `json:"autoGenerated"`
	Status        string             `json:"status"`
	ErrorMessage  string             `json:"errorMessage,omitempty"`
	WorkDir       string             `json:"workDir,omitempty"`
	Sessions      []*sessionResponse `json:"sessions"`
}

func deriveSessionStatusAndError(sess *service.Session) (string, string) {
	if sess.Status == model.SessionStatusRemoving || sess.Status == model.SessionStatusRemoved {
		return sess.Status, ""
	}

	commitStatus := strings.TrimSpace(sess.CommitStatus)
	commitOperation := strings.TrimSpace(sess.CommitOperation)
	switch {
	case commitStatus == "":
		if sess.Status == model.SessionStatusError {
			return sess.Status, sess.ErrorMessage
		}
		return sess.Status, ""
	case strings.EqualFold(commitStatus, model.CommitStatusFailed), strings.EqualFold(commitStatus, "false"):
		errorMessage := sess.CommitError
		if errorMessage == "" {
			errorMessage = sess.ErrorMessage
		}
		return model.SessionStatusError, errorMessage
	case strings.EqualFold(commitStatus, model.CommitStatusCompleted) && strings.EqualFold(commitOperation, service.CommitOperationCommit):
		return "committed", ""
	case strings.EqualFold(commitStatus, model.CommitStatusCompleted) && strings.EqualFold(commitOperation, service.CommitOperationRebase):
		return "rebased", ""
	default:
		return commitStatus, ""
	}
}

func mapSessionResponse(sess *service.Session) *sessionResponse {
	if sess == nil {
		return nil
	}

	status, errorMessage := deriveSessionStatusAndError(sess)
	return &sessionResponse{
		ID:              sess.ID,
		ProjectID:       sess.ProjectID,
		Name:            sess.Name,
		DisplayName:     sess.DisplayName,
		Description:     sess.Description,
		CreatedAt:       sess.CreatedAt,
		Timestamp:       sess.Timestamp,
		Status:          status,
		BaseCommit:      sess.BaseCommit,
		AppliedCommit:   sess.AppliedCommit,
		ErrorMessage:    errorMessage,
		Files:           sess.Files,
		WorkspaceID:     sess.WorkspaceID,
		WorkspacePath:   sess.WorkspacePath,
		WorkspaceCommit: sess.WorkspaceCommit,
	}
}

func mapSessionResponses(sessions []*service.Session) []*sessionResponse {
	result := make([]*sessionResponse, len(sessions))
	for i, sess := range sessions {
		result[i] = mapSessionResponse(sess)
	}
	return result
}

func mapWorkspaceResponse(workspace *service.Workspace) *workspaceResponse {
	if workspace == nil {
		return nil
	}

	sessions := make([]*sessionResponse, len(workspace.Sessions))
	for i, sess := range workspace.Sessions {
		sessions[i] = mapSessionResponse(sess)
	}

	return &workspaceResponse{
		ID:            workspace.ID,
		Path:          workspace.Path,
		DisplayName:   workspace.DisplayName,
		SourceType:    workspace.SourceType,
		Provider:      workspace.Provider,
		AutoGenerated: workspace.AutoGenerated,
		Status:        workspace.Status,
		ErrorMessage:  workspace.ErrorMessage,
		WorkDir:       workspace.WorkDir,
		Sessions:      sessions,
	}
}

func mapWorkspaceResponses(workspaces []*service.Workspace) []*workspaceResponse {
	result := make([]*workspaceResponse, len(workspaces))
	for i, workspace := range workspaces {
		result[i] = mapWorkspaceResponse(workspace)
	}
	return result
}

// GetSession returns a single session
func (h *Handler) GetSession(w http.ResponseWriter, r *http.Request) {
	sessionID := chi.URLParam(r, "sessionId")

	session, err := h.sessionService.GetSession(r.Context(), sessionID)
	if err != nil {
		h.Error(w, http.StatusNotFound, "Session not found")
		return
	}

	h.JSON(w, http.StatusOK, mapSessionResponse(session))
}

// UpdateSession updates a session
func (h *Handler) UpdateSession(w http.ResponseWriter, r *http.Request) {
	sessionID := chi.URLParam(r, "sessionId")

	// Parse as map first to detect which fields are present
	var rawReq map[string]interface{}
	if err := h.DecodeJSON(r, &rawReq); err != nil {
		h.Error(w, http.StatusBadRequest, "Invalid request body")
		return
	}

	// Extract fields
	name, _ := rawReq["name"].(string)
	status, _ := rawReq["status"].(string)

	// Handle displayName: only process if key is present
	var displayName *string
	if displayNameValue, hasDisplayName := rawReq["displayName"]; hasDisplayName {
		if displayNameValue == nil {
			// Explicitly set to null - pass empty string to clear it
			emptyStr := ""
			displayName = &emptyStr
		} else if str, ok := displayNameValue.(string); ok {
			displayName = &str
		}
	}

	session, err := h.sessionService.UpdateSession(r.Context(), sessionID, name, displayName, status)
	if err != nil {
		h.Error(w, http.StatusInternalServerError, "Failed to update session")
		return
	}

	h.JSON(w, http.StatusOK, mapSessionResponse(session))
}

// DeleteSession initiates async deletion of a session
func (h *Handler) DeleteSession(w http.ResponseWriter, r *http.Request) {
	sessionID := chi.URLParam(r, "sessionId")
	ctx := r.Context()
	projectID := middleware.GetProjectID(ctx)

	if err := h.sessionService.DeleteSession(ctx, projectID, sessionID, h.jobQueue); err != nil {
		if strings.Contains(err.Error(), "not found") {
			h.Error(w, http.StatusNotFound, "Session not found")
			return
		}
		h.Error(w, http.StatusInternalServerError, "Failed to initiate session deletion")
		return
	}

	h.JSON(w, http.StatusOK, map[string]bool{"success": true})
}

// ListSessions returns all sessions for a project.
func (h *Handler) ListSessions(w http.ResponseWriter, r *http.Request) {
	projectID := middleware.GetProjectID(r.Context())

	sessions, err := h.sessionService.ListSessionsByProject(r.Context(), projectID)
	if err != nil {
		h.Error(w, http.StatusInternalServerError, "Failed to list sessions")
		return
	}

	h.JSON(w, http.StatusOK, map[string]any{"sessions": mapSessionResponses(sessions)})
}

// CommitSession initiates async commit of a session
func (h *Handler) CommitSession(w http.ResponseWriter, r *http.Request) {
	sessionID := chi.URLParam(r, "sessionId")
	ctx := r.Context()
	projectID := middleware.GetProjectID(ctx)

	if err := h.sessionService.CommitSession(ctx, projectID, sessionID, h.jobQueue); err != nil {
		if strings.Contains(err.Error(), "not found") {
			h.Error(w, http.StatusNotFound, "Session not found")
			return
		}
		if errors.Is(err, service.ErrSessionOperationInProgress) {
			h.Error(w, http.StatusConflict, "Session operation already in progress")
			return
		}
		h.Error(w, http.StatusInternalServerError, "Failed to initiate session commit")
		return
	}

	h.JSON(w, http.StatusOK, map[string]bool{"success": true})
}

// RebaseSession initiates async rebase of a session
func (h *Handler) RebaseSession(w http.ResponseWriter, r *http.Request) {
	sessionID := chi.URLParam(r, "sessionId")
	ctx := r.Context()
	projectID := middleware.GetProjectID(ctx)

	if err := h.sessionService.RebaseSession(ctx, projectID, sessionID, h.jobQueue); err != nil {
		if strings.Contains(err.Error(), "not found") {
			h.Error(w, http.StatusNotFound, "Session not found")
			return
		}
		if errors.Is(err, service.ErrSessionOperationInProgress) {
			h.Error(w, http.StatusConflict, "Session operation already in progress")
			return
		}
		h.Error(w, http.StatusInternalServerError, "Failed to initiate session rebase")
		return
	}

	h.JSON(w, http.StatusOK, map[string]bool{"success": true})
}

// CreateSessionRequest represents the request body for creating a session without sending a message.
type CreateSessionRequest struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspaceId,omitempty"`
}

func (h *Handler) resolveWorkspaceIDForNewSession(
	ctx context.Context,
	projectID string,
	workspaceID string,
) (string, error) {
	if workspaceID != "" {
		return workspaceID, nil
	}

	if h.cfg == nil || h.workspaceService == nil || h.jobQueue == nil || h.store == nil {
		return "", fmt.Errorf("automatic workspace creation is unavailable")
	}
	if strings.TrimSpace(h.cfg.WorkspaceDir) == "" {
		return "", fmt.Errorf("automatic workspace creation is unavailable: workspace dir is not configured")
	}

	autoPath := filepath.Join(h.cfg.WorkspaceDir, fmt.Sprintf("empty-workspace-%s", uuid.NewString()))
	workspace, err := h.workspaceService.CreateWorkspace(ctx, projectID, autoPath, "local", "")
	if err != nil {
		return "", fmt.Errorf("failed to create automatic workspace: %w", err)
	}

	workspaceModel, err := h.store.GetWorkspaceByID(ctx, workspace.ID)
	if err != nil {
		return "", fmt.Errorf("failed to load automatic workspace: %w", err)
	}
	workspaceModel.AutoGenerated = true
	if err := h.store.UpdateWorkspace(ctx, workspaceModel); err != nil {
		return "", fmt.Errorf("failed to flag automatic workspace: %w", err)
	}

	if err := h.jobQueue.Enqueue(ctx, jobs.WorkspaceInitPayload{ProjectID: projectID, WorkspaceID: workspace.ID}); err != nil {
		return "", fmt.Errorf("failed to enqueue automatic workspace initialization: %w", err)
	}

	return workspace.ID, nil
}

// CreateSession creates a new session without sending a chat message.
// This spins up a sandbox but does not invoke the LLM.
// POST /api/projects/{projectId}/sessions
func (h *Handler) CreateSession(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	projectID := middleware.GetProjectID(ctx)

	var req CreateSessionRequest
	if err := h.DecodeJSON(r, &req); err != nil {
		h.Error(w, http.StatusBadRequest, "Invalid request body")
		return
	}

	if req.ID == "" {
		h.Error(w, http.StatusBadRequest, "id is required")
		return
	}

	workspaceID, err := h.resolveWorkspaceIDForNewSession(ctx, projectID, req.WorkspaceID)
	if err != nil {
		h.Error(w, http.StatusInternalServerError, err.Error())
		return
	}

	sessionID, err := h.chatService.NewSession(ctx, service.NewSessionRequest{
		SessionID:   req.ID,
		ProjectID:   projectID,
		WorkspaceID: workspaceID,
		Messages:    nil,
	})
	if err != nil {
		h.Error(w, http.StatusBadRequest, err.Error())
		return
	}

	h.JSON(w, http.StatusOK, map[string]string{"id": sessionID})
}
