package service

import (
	"context"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	gitrepo "github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/object"

	"github.com/obot-platform/discobot/server/internal/events"
	discogit "github.com/obot-platform/discobot/server/internal/git"
	"github.com/obot-platform/discobot/server/internal/model"
	"github.com/obot-platform/discobot/server/internal/store"
)

// expandPath expands ~ to the user's home directory and cleans the path.
// For paths starting with ~, it replaces ~ with $HOME.
// All paths are cleaned using filepath.Clean to remove redundant elements.
func expandPath(path string) (string, error) {
	if strings.HasPrefix(path, "~") {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home directory: %w", err)
		}
		path = filepath.Join(home, path[1:])
	}
	return filepath.Clean(path), nil
}

const (
	// LocalWorkspaceClassificationNew indicates a local workspace path that does not
	// exist yet but can be created because its parent directory exists.
	LocalWorkspaceClassificationNew = "new"
	// LocalWorkspaceClassificationEmpty indicates an existing, empty directory.
	LocalWorkspaceClassificationEmpty = "empty"
	// LocalWorkspaceClassificationExistingGit indicates an existing git repository.
	LocalWorkspaceClassificationExistingGit = "existing_git"
	// LocalWorkspaceClassificationInvalid indicates a path that is not usable as a workspace.
	LocalWorkspaceClassificationInvalid = "invalid"
)

func classifyLocalWorkspacePath(path string) (string, string, error) {
	expandedPath, err := expandPath(path)
	if err != nil {
		return "", LocalWorkspaceClassificationInvalid, fmt.Errorf("failed to expand path: %w", err)
	}

	info, statErr := os.Stat(expandedPath)
	if os.IsNotExist(statErr) {
		parentDir := filepath.Dir(expandedPath)
		parentInfo, parentErr := os.Stat(parentDir)
		if parentErr != nil {
			if os.IsNotExist(parentErr) {
				return expandedPath, LocalWorkspaceClassificationInvalid, fmt.Errorf("parent directory does not exist: %s", parentDir)
			}
			return expandedPath, LocalWorkspaceClassificationInvalid, fmt.Errorf("failed to access parent directory: %w", parentErr)
		}
		if !parentInfo.IsDir() {
			return expandedPath, LocalWorkspaceClassificationInvalid, fmt.Errorf("parent path is not a directory: %s", parentDir)
		}
		return expandedPath, LocalWorkspaceClassificationNew, nil
	}

	if statErr != nil {
		return expandedPath, LocalWorkspaceClassificationInvalid, fmt.Errorf("failed to access directory: %w", statErr)
	}

	if !info.IsDir() {
		return expandedPath, LocalWorkspaceClassificationInvalid, fmt.Errorf("path is not a directory: %s", expandedPath)
	}

	entries, err := os.ReadDir(expandedPath)
	if err != nil {
		return expandedPath, LocalWorkspaceClassificationInvalid, fmt.Errorf("failed to read directory: %w", err)
	}
	if len(entries) == 0 {
		return expandedPath, LocalWorkspaceClassificationEmpty, nil
	}

	if _, err := gitrepo.PlainOpen(expandedPath); err == nil {
		return expandedPath, LocalWorkspaceClassificationExistingGit, nil
	} else if !errors.Is(err, gitrepo.ErrRepositoryNotExists) {
		return expandedPath, LocalWorkspaceClassificationInvalid, fmt.Errorf("failed to inspect git repository: %w", err)
	}

	return expandedPath, LocalWorkspaceClassificationInvalid, fmt.Errorf("not a git repository: directory must contain a .git folder")
}

// Workspace represents a workspace with its sessions (for API responses)
type Workspace struct {
	ID            string     `json:"id"`
	Path          string     `json:"path"`
	DisplayName   *string    `json:"displayName,omitempty"`
	SourceType    string     `json:"sourceType"`
	Provider      string     `json:"provider,omitempty"`
	AutoGenerated bool       `json:"autoGenerated"`
	Status        string     `json:"status"`
	ErrorMessage  string     `json:"errorMessage,omitempty"`
	WorkDir       string     `json:"workDir,omitempty"`
	Sessions      []*Session `json:"sessions"`
}

// WorkspaceService handles workspace operations
type WorkspaceService struct {
	store       *store.Store
	gitProvider discogit.Provider
	eventBroker *events.Broker
}

// NewWorkspaceService creates a new workspace service
func NewWorkspaceService(s *store.Store, gitProvider discogit.Provider, eventBroker *events.Broker) *WorkspaceService {
	return &WorkspaceService{
		store:       s,
		gitProvider: gitProvider,
		eventBroker: eventBroker,
	}
}

// ListWorkspaces returns all workspaces for a project
func (s *WorkspaceService) ListWorkspaces(ctx context.Context, projectID string) ([]*Workspace, error) {
	dbWorkspaces, err := s.store.ListWorkspacesByProject(ctx, projectID)
	if err != nil {
		return nil, fmt.Errorf("failed to list workspaces: %w", err)
	}

	workspaces := make([]*Workspace, len(dbWorkspaces))
	for i, ws := range dbWorkspaces {
		workspaces[i] = s.mapWorkspace(ctx, ws)
	}
	return workspaces, nil
}

// GetWorkspace returns a single workspace by ID
func (s *WorkspaceService) GetWorkspace(ctx context.Context, workspaceID string) (*Workspace, error) {
	ws, err := s.store.GetWorkspaceByID(ctx, workspaceID)
	if err != nil {
		return nil, fmt.Errorf("failed to get workspace: %w", err)
	}

	return s.mapWorkspace(ctx, ws), nil
}

func isLocalWorkspaceSourceType(sourceType string) bool {
	return sourceType == model.WorkspaceSourceTypeLocal ||
		sourceType == model.WorkspaceSourceTypeManaged
}

// CreateWorkspace creates a new workspace with initializing status.
// For local paths: if the directory does not exist or is empty, it will be
// created and initialized as a new git repository automatically.
func (s *WorkspaceService) CreateWorkspace(ctx context.Context, projectID, path, sourceType, provider string) (*Workspace, error) {
	// Expand and validate local paths.
	if isLocalWorkspaceSourceType(sourceType) {
		normalizedPath, classification, err := classifyLocalWorkspacePath(path)
		if err != nil {
			return nil, err
		}
		path = normalizedPath

		if classification == LocalWorkspaceClassificationNew || classification == LocalWorkspaceClassificationEmpty {
			createdDirectory := classification == LocalWorkspaceClassificationNew
			if createdDirectory {
				if err := os.MkdirAll(path, 0755); err != nil {
					return nil, fmt.Errorf("failed to create directory: %w", err)
				}
			}

			if err := s.initializeLocalRepository(ctx, path); err != nil {
				if createdDirectory {
					_ = os.RemoveAll(path)
				}
				return nil, err
			}

			log.Printf("Initialized new git repository: %s", path)
		}
	}

	ws := &model.Workspace{
		ProjectID:  projectID,
		Path:       path,
		SourceType: sourceType,
		Provider:   provider,
		Status:     model.WorkspaceStatusInitializing,
	}
	if err := s.store.CreateWorkspace(ctx, ws); err != nil {
		return nil, fmt.Errorf("failed to create workspace: %w", err)
	}

	return s.mapWorkspace(ctx, ws), nil
}

// ValidateLocalWorkspacePath validates a user-provided local workspace path.
// It returns the expanded/normalized path and a classification describing whether
// the path points to a new directory, an empty directory, an existing git
// repository, or an invalid location.
func (s *WorkspaceService) ValidateLocalWorkspacePath(path string) (string, string, error) {
	return classifyLocalWorkspacePath(path)
}

func (s *WorkspaceService) initializeLocalRepository(ctx context.Context, path string) error {
	repo, err := gitrepo.PlainInit(path, false)
	if err != nil {
		return fmt.Errorf("failed to initialize git repository: %w", err)
	}

	worktree, err := repo.Worktree()
	if err != nil {
		return fmt.Errorf("failed to open git worktree: %w", err)
	}

	gitUserName := "Discobot"
	gitUserEmail := "discobot@localhost"
	if s.gitProvider != nil {
		providerName, providerEmail := s.gitProvider.GetUserConfig(ctx)
		if providerName != "" {
			gitUserName = providerName
		}
		if providerEmail != "" {
			gitUserEmail = providerEmail
		}
	}

	signature := &object.Signature{
		Name:  gitUserName,
		Email: gitUserEmail,
		When:  time.Now(),
	}

	if _, err := worktree.Commit("Initial commit", &gitrepo.CommitOptions{
		Author:            signature,
		Committer:         signature,
		AllowEmptyCommits: true,
	}); err != nil {
		return fmt.Errorf("failed to create initial commit: %w", err)
	}

	return nil
}

// UpdateWorkspace updates a workspace
func (s *WorkspaceService) UpdateWorkspace(ctx context.Context, workspaceID, path string) (*Workspace, error) {
	ws, err := s.store.GetWorkspaceByID(ctx, workspaceID)
	if err != nil {
		return nil, fmt.Errorf("failed to get workspace: %w", err)
	}

	// Expand ~ to home directory for local paths
	if isLocalWorkspaceSourceType(ws.SourceType) {
		expandedPath, err := expandPath(path)
		if err != nil {
			return nil, fmt.Errorf("failed to expand path: %w", err)
		}
		path = expandedPath
	}

	ws.Path = path
	if err := s.store.UpdateWorkspace(ctx, ws); err != nil {
		return nil, fmt.Errorf("failed to update workspace: %w", err)
	}

	return s.mapWorkspace(ctx, ws), nil
}

// mapWorkspace converts a model.Workspace to a service.Workspace
func (s *WorkspaceService) mapWorkspace(ctx context.Context, ws *model.Workspace) *Workspace {
	result := &Workspace{
		ID:            ws.ID,
		Path:          ws.Path,
		DisplayName:   ws.DisplayName,
		SourceType:    ws.SourceType,
		Provider:      ws.Provider,
		AutoGenerated: ws.AutoGenerated,
		Status:        ws.Status,
		Sessions:      []*Session{},
	}
	if ws.ErrorMessage != nil {
		result.ErrorMessage = *ws.ErrorMessage
	}
	// Get working directory path from git provider if available
	if s.gitProvider != nil {
		result.WorkDir = s.gitProvider.GetWorkDir(ctx, ws.ID)
	}
	return result
}

// DeleteWorkspace deletes a workspace. If deleteFiles is true, also removes the
// working directory from disk.
func (s *WorkspaceService) DeleteWorkspace(ctx context.Context, workspaceID string, deleteFiles bool) error {
	// Delete files first if requested (before removing DB record)
	if deleteFiles && s.gitProvider != nil {
		if err := s.gitProvider.RemoveWorkspace(ctx, workspaceID); err != nil {
			log.Printf("Warning: failed to remove workspace files for %s: %v", workspaceID, err)
			// Continue with DB deletion even if file deletion fails
		}
	}

	return s.store.DeleteWorkspace(ctx, workspaceID)
}

// GetWorkspaceWithSessions returns a workspace with all its sessions
func (s *WorkspaceService) GetWorkspaceWithSessions(ctx context.Context, workspaceID string) (*Workspace, error) {
	workspace, err := s.GetWorkspace(ctx, workspaceID)
	if err != nil {
		return nil, err
	}

	// Create session service to fetch sessions
	// Note: git service, sandbox provider, sandbox service, and job enqueuer are nil since ListSessionsByWorkspace doesn't need them
	sessionSvc := NewSessionService(s.store, nil, nil, nil, s.eventBroker, nil)
	sessions, err := sessionSvc.ListSessionsByWorkspace(ctx, workspaceID)
	if err != nil {
		return nil, err
	}

	workspace.Sessions = sessions
	return workspace, nil
}

// Initialize performs workspace initialization by setting up the git working directory.
// This is called by the dispatcher when processing a workspace_init job.
func (s *WorkspaceService) Initialize(ctx context.Context, workspaceID string) error {
	if s.gitProvider == nil {
		return fmt.Errorf("git provider not configured")
	}

	// Get workspace
	ws, err := s.store.GetWorkspaceByID(ctx, workspaceID)
	if err != nil {
		return fmt.Errorf("workspace not found: %w", err)
	}

	// Update status to cloning (for git workspaces) or initializing
	if discogit.IsGitURL(ws.Path) {
		s.updateStatusWithEvent(ctx, ws.ProjectID, workspaceID, model.WorkspaceStatusCloning, nil)
	}

	// Initialize the workspace (clone/setup git repo)
	_, commit, err := s.gitProvider.EnsureWorkspace(ctx, ws.ProjectID, workspaceID, ws.Path, "")
	if err != nil {
		errMsg := fmt.Sprintf("failed to initialize workspace: %v", err)
		s.updateStatusWithEvent(ctx, ws.ProjectID, workspaceID, model.WorkspaceStatusError, &errMsg)
		return fmt.Errorf("workspace initialization failed: %w", err)
	}

	// Update workspace to ready status
	ws.Status = model.WorkspaceStatusReady
	ws.ErrorMessage = nil
	if err := s.store.UpdateWorkspace(ctx, ws); err != nil {
		log.Printf("Failed to update workspace %s: %v", workspaceID, err)
	}

	// Emit success event
	if s.eventBroker != nil {
		if err := s.eventBroker.PublishWorkspaceUpdated(ctx, ws.ProjectID, workspaceID, model.WorkspaceStatusReady); err != nil {
			log.Printf("Failed to publish workspace update event: %v", err)
		}
	}

	log.Printf("Workspace %s initialized successfully (commit: %s)", workspaceID, commit)
	return nil
}

// updateStatusWithEvent updates workspace status and emits an SSE event.
func (s *WorkspaceService) updateStatusWithEvent(ctx context.Context, projectID, workspaceID, status string, errorMsg *string) {
	// Update workspace in database
	ws, err := s.store.GetWorkspaceByID(ctx, workspaceID)
	if err != nil {
		log.Printf("Failed to get workspace %s for status update: %v", workspaceID, err)
		return
	}

	ws.Status = status
	ws.ErrorMessage = errorMsg
	if err := s.store.UpdateWorkspace(ctx, ws); err != nil {
		log.Printf("Failed to update workspace %s status to %s: %v", workspaceID, status, err)
	}

	// Emit SSE event
	if s.eventBroker != nil {
		if err := s.eventBroker.PublishWorkspaceUpdated(ctx, projectID, workspaceID, status); err != nil {
			log.Printf("Failed to publish workspace update event: %v", err)
		}
	}
}
